import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { useRouter, useSearchParams } from '../cockpit/router';
import { Button } from '@/components/ui/button';
import { CompanionBadge } from '@/components/cockpit/companion-mark';
import { MetricCard, PageHeading, StateBadge, Surface } from '@/components/cockpit/page-elements';
import { ArrowRight, FileSpreadsheet, FileText, Gauge, GitCompareArrows, History, LineChart, Target, WalletCards } from '@/components/ui/site-icon';
import { errorText, intentApi, statusLabel } from '../api';
import type { FinancialSeries } from '../workshopTypes';
import type { Version } from '../types';
import type { Catalog, Comparison, ConnectedProps, Metric } from './types';
import { textValue, useCaseData } from './data';
import { Legacy, ReadError, SheetPanel, sheetHref } from './SheetPanel';

export const palettes = [
  { id: 'indigo', label: 'Clarté', accent: '#5263eb', deep: '#27357f', soft: '#e9edff' },
  { id: 'lagoon', label: 'Élan', accent: '#188c87', deep: '#145f64', soft: '#e1f5f2' },
  { id: 'copper', label: 'Caractère', accent: '#b96843', deep: '#73422f', soft: '#f8e9e1' },
];
export type PresentationPreferences = { palette: string; firstName: string; logo: string };
const inputClass = 'mt-2 min-h-11 w-full rounded-2xl border border-slate-200 bg-white px-4 py-2 text-base outline-none focus:ring-2 focus:ring-[var(--brand)]';
const date = (value?: string) => value ? new Date(value).toLocaleString('fr-FR') : 'Date non disponible';

export function Personalization({ preferences, change, error }: { preferences: PresentationPreferences; change: (next: PresentationPreferences) => void; error: string }) {
  const [fileError, setFileError] = useState('');
  async function upload(file: File | undefined) {
    if (!file) return;
    if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || file.size > 1_000_000) { setFileError('Choisissez une image PNG, JPEG ou WebP de moins de 1 Mo.'); return; }
    setFileError('');
    const reader = new FileReader(); reader.onload = () => change({ ...preferences, logo: String(reader.result) });
    reader.onerror = () => setFileError('Cette image ne peut pas être lue.'); reader.readAsDataURL(file);
  }
  return <Surface className="mt-7" variant="glass"><h2 className="text-xl font-semibold">Votre présentation</h2><p className="mt-2 text-slate-500">Ces préférences restent sur ce navigateur et ne modifient aucun chiffre.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Votre prénom<input className={inputClass} maxLength={80} value={preferences.firstName} onChange={e => change({ ...preferences, firstName: e.target.value })}/></label><label className="text-sm font-medium">Logo local<input className={inputClass} type="file" accept="image/png,image/jpeg,image/webp" onChange={e => void upload(e.target.files?.[0])}/></label></div><fieldset className="mt-6"><legend className="text-sm font-medium">Palette</legend><div className="mt-3 flex flex-wrap gap-3">{palettes.map(palette => <button key={palette.id} aria-pressed={preferences.palette === palette.id} className="flex min-h-14 items-center gap-3 rounded-2xl border border-white bg-white/80 px-5 shadow-sm aria-pressed:ring-2 aria-pressed:ring-[var(--brand)]" onClick={() => change({ ...preferences, palette: palette.id })}><span className="size-6 rounded-full" style={{ background: palette.accent }}/>{palette.label}</button>)}</div></fieldset>{preferences.logo && <Button variant="ghost" className="mt-4 min-h-11 rounded-full" onClick={() => change({ ...preferences, logo: '' })}>Retirer le logo</Button>}{(error || fileError) && <p role="alert" className="mt-4 text-red-800">{error || fileError}</p>}</Surface>;
}

function MetricGrid({ metrics }: { metrics: Metric[] }) {
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric, index) => <MetricCard key={metric.id} label={metric.label} value={metric.id === 'cash_break_date' && metric.value === null && metric.status === 'CALCULE' ? 'Aucune sur la période' : textValue(metric.value) + (metric.value != null && metric.unit === 'EUR' ? ' €' : metric.value != null && metric.unit && !['EUR', 'mois'].includes(metric.unit) ? ' ' + metric.unit : '')} detail={[metric.period, statusLabel(metric.status)].filter(Boolean).join(' · ')} icon={[LineChart, Target, WalletCards, Gauge][index % 4]} tone={metric.value == null ? 'warning' : 'brand'}/>)}</div>;
}

function CashSeries({ series }: { series: FinancialSeries | undefined }) {
  if (!series) return <p className="text-slate-500">La série mensuelle n’est pas disponible.</p>;
  const points = series.values.map((value, index) => ({ value, period: series.categories[index] }));
  const usable = points.filter((point): point is { value: number; period: string } => typeof point.value === 'number' && Number.isFinite(point.value));
  const min = usable.length ? Math.min(...usable.map(p => p.value)) : 0, max = usable.length ? Math.max(...usable.map(p => p.value)) : 1;
  const x = (index: number) => 12 + (points.length <= 1 ? 348 : index * 696 / (points.length - 1));
  const y = (value: number) => 22 + (max - value) * 130 / Math.max(1, max - min);
  let path = '', continuous = false;
  points.forEach((point, index) => { if (typeof point.value !== 'number' || !Number.isFinite(point.value)) { continuous = false; return; } path += `${continuous ? 'L' : 'M'}${x(index)} ${y(point.value)} `; continuous = true; });
  return <><div className="mb-4 flex flex-wrap justify-between gap-2"><h2 className="text-xl font-semibold">{series.label}</h2><StateBadge tone="neutral">{statusLabel(series.status)}</StateBadge></div>{usable.length ? <svg role="img" aria-label={series.label + ', données mensuelles du dossier, détail dans le tableau'} viewBox="0 0 720 180" className="h-44 w-full"><path d={path} stroke="var(--brand)" fill="none" strokeWidth="3" strokeLinecap="round"/>{points.map((point, index) => typeof point.value === 'number' ? <circle key={point.period} cx={x(index)} cy={y(point.value)} r="3.5" fill="var(--brand)"><title>{point.period + ' : ' + textValue(point.value) + ' ' + series.unit}</title></circle> : null)}</svg> : <p className="rounded-2xl bg-slate-50 p-5 leading-7 text-slate-500">Les mois seront affichés après saisie, qualification et recalcul. Les données manquantes restent à compléter.</p>}<details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Lire les données mensuelles</summary><div className="mt-3 max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Mois</th><th className="p-2">{series.label} ({series.unit})</th></tr></thead><tbody>{points.map(point => <tr key={point.period} className="border-t"><th className="p-2 font-normal">{point.period}</th><td className="p-2">{textValue(point.value)}</td></tr>)}</tbody></table></div></details></>;
}

function CashComparison({ reference, simulation }: { reference?: FinancialSeries; simulation?: FinancialSeries }) {
  if (!reference || !simulation) return <><p className="mb-4 text-slate-500">Les deux séries mensuelles doivent être disponibles pour comparer leur évolution.</p><CashSeries series={simulation}/></>;
  if (reference.unit !== simulation.unit) return <p role="alert" className="text-amber-900">Les unités des séries diffèrent : la comparaison nécessite une correspondance explicite.</p>;
  const periods = [...new Set([...reference.categories, ...simulation.categories])].sort();
  const pairs = [reference, simulation].map(series => new Map(series.categories.map((period, i) => [period, series.values[i]])));
  const numbers = [...reference.values, ...simulation.values].filter((value): value is number => typeof value === 'number' && Number.isFinite(value));
  const min = numbers.length ? Math.min(...numbers) : 0, max = numbers.length ? Math.max(...numbers) : 0;
  const x = (index: number) => 76 + (periods.length <= 1 ? 290 : index * 580 / (periods.length - 1));
  const y = (value: number) => 28 + (max - value) * 136 / Math.max(1, max - min);
  const paths = pairs.map(values => { let result = '', continuous = false; periods.forEach((period, index) => { const value = values.get(period); if (typeof value !== 'number' || !Number.isFinite(value)) { continuous = false; return; } result += `${continuous ? 'L' : 'M'}${x(index)} ${y(value)} `; continuous = true; }); return result; });
  const axis = (value: number) => new Intl.NumberFormat('fr-FR', { notation: 'compact', maximumFractionDigits: 1 }).format(value);
  return <><h2 className="text-xl font-semibold">Trésorerie : référence et simulation</h2><p className="mt-2 text-sm text-slate-500">Calendrier et échelle communs · {reference.unit}. Une période absente interrompt la courbe et ne devient pas un zéro.</p><div className="mt-4 flex flex-wrap gap-5 text-sm"><span className="flex items-center gap-2"><span className="h-0.5 w-7 border-t-2 border-dashed border-slate-500"/>Référence actuelle · {statusLabel(reference.status)}</span><span className="flex items-center gap-2"><span className="h-0.5 w-7 bg-[var(--brand)]"/>Simulation · {statusLabel(simulation.status)}</span></div>{numbers.length ? <svg role="img" aria-label="Référence actuelle et simulation de trésorerie sur le même calendrier et la même échelle, détail dans le tableau" viewBox="0 0 720 210" className="mt-4 h-52 w-full"><line x1="76" y1="164" x2="656" y2="164" stroke="#cbd5e1"/><text x="66" y="32" textAnchor="end" fontSize="13" fill="#64748b">{axis(max)}</text><text x="66" y="168" textAnchor="end" fontSize="13" fill="#64748b">{axis(min)}</text><text x="76" y="194" fontSize="13" fill="#64748b">{periods[0]}</text><text x="656" y="194" textAnchor="end" fontSize="13" fill="#64748b">{periods.at(-1)}</text>{paths.map((path, index) => <path key={index} d={path} stroke={index ? 'var(--brand)' : '#64748b'} fill="none" strokeWidth={index ? 3.5 : 2.5} strokeDasharray={index ? undefined : '7 5'} strokeLinecap="round"/>)}{pairs.map((values, seriesIndex) => periods.map((period, index) => { const value = values.get(period); return typeof value === 'number' && Number.isFinite(value) ? <circle key={seriesIndex + period} cx={x(index)} cy={y(value)} r="3" fill={seriesIndex ? 'var(--brand)' : '#64748b'}><title>{`${seriesIndex ? 'Simulation' : 'Référence actuelle'} · ${period} : ${textValue(value)} ${reference.unit}`}</title></circle> : null; }))}</svg> : <p className="mt-4 rounded-2xl bg-slate-50 p-5 text-slate-500">Les résultats mensuels restent à compléter ou à recalculer.</p>}<details className="mt-4"><summary className="cursor-pointer text-sm font-medium">Comparer les montants mois par mois</summary><div className="mt-3 max-h-96 overflow-auto"><table className="w-full text-left text-sm" aria-label="Trésorerie comparée par mois"><thead><tr><th className="p-3">Mois · {reference.unit}</th><th className="p-3">Référence actuelle</th><th className="p-3">Simulation</th></tr></thead><tbody>{periods.map(period => <tr key={period} className="border-t"><th className="p-3 font-normal">{period}</th>{pairs.map((values, i) => <td key={i} className="p-3">{values.has(period) ? textValue(values.get(period)) : 'Hors période'}</td>)}</tr>)}</tbody></table></div></details></>;
}

export function Home({ app, firstName, companyName, catalog, discuss }: { app: ConnectedProps; firstName: string; companyName: string; catalog: Catalog | null; discuss: (sheet?: string, prompt?: string) => void }) {
  const router = useRouter();
  const remote = useCaseData<Comparison>(app.caseId, '/scenarios/compare', app.refresh);
  const reference = remote.data?.scenarios?.find(item => item.case_id === app.caseId || item.id === app.caseId);
  const metrics = reference?.metrics?.filter(item => ['revenue', 'gross_margin', 'cash_min', 'financing_need'].includes(item.id)) || [];
  return <div className="space-y-7"><PageHeading eyebrow="Aujourd’hui" title={firstName ? `Bonjour ${firstName}, que décidons-nous aujourd’hui ?` : 'Vos chiffres au service de vos décisions'} description={`${companyName} : retrouvez votre dossier, ses points à compléter et vos simulations.`}/>
    <div className="grid items-start gap-6 xl:grid-cols-[1.4fr_1fr]"><Surface className="overflow-hidden" variant="tinted" depth={2}><div className="flex items-center gap-4"><CompanionBadge size="large" motion="awake"/><div><p className="text-sm font-medium text-[var(--brand)]">Votre compagnon de décision</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Une prochaine étape, à votre rythme.</h2></div></div><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">{app.draft.operations?.length ? `${app.draft.operations.length} modification(s) attendent dans le brouillon partagé. Examinez leurs sources et leurs conséquences avant de les appliquer.` : 'Décrivez votre entreprise, ajoutez vos documents, puis travaillez sur les hypothèses utiles à votre projet.'}</p><div className="mt-6 flex flex-wrap gap-3"><Button className="min-h-12 rounded-full px-6" onClick={() => router.push(app.draft.operations?.length ? '/simulations' : '/parcours')}>{app.draft.operations?.length ? 'Préparer une simulation' : 'Reprendre mon parcours'}<ArrowRight/></Button><Button variant="outline" className="min-h-12 rounded-full px-6" onClick={() => discuss(app.sheetName, 'Quelles informations manquent dans ce dossier et quelle est la prochaine étape utile ?')}>Demander au compagnon</Button></div></Surface><Surface variant="glass"><h2 className="text-lg font-semibold">Votre dossier aujourd’hui</h2><dl className="mt-4 space-y-3 text-sm">{[['Version', 'Révision ' + (app.active?.revision ?? 0)], ['Sources', String(app.sources.length)], ['Feuilles du modèle', String(catalog?.sheets.length ?? app.sheets.length)], ['État des résultats', statusLabel(app.active?.calculation_status)]].map(([label, value]) => <div key={label} className="flex justify-between gap-3 border-b border-slate-200/60 pb-3"><dt className="text-slate-500">{label}</dt><dd className="text-right font-medium">{value}</dd></div>)}</dl><Button variant="ghost" className="mt-4 min-h-11 rounded-full" onClick={() => router.push('/documents')}>Consulter mes documents<ArrowRight/></Button></Surface></div>
    <ReadError message={remote.error} retry={remote.retry}/>{remote.loading && !remote.data && <p role="status">Lecture des indicateurs du dossier…</p>}
    {!!metrics.length && <MetricGrid metrics={metrics}/>}<Surface><CashSeries series={reference?.series?.find(series => series.id === 'cash')}/></Surface>
    <div className="grid gap-4 md:grid-cols-3">{[{ title: 'Construire', description: 'Réunir les hypothèses et leurs sources.', path: '/parcours', icon: FileSpreadsheet }, { title: 'Comparer', description: 'Simuler une décision sur une copie indépendante.', path: '/simulations', icon: GitCompareArrows }, { title: 'Partager', description: 'Préparer votre Excel et vos rapports actualisés.', path: '/livrables', icon: FileText }].map(({ title, description, path, icon: CardIcon }) => <Surface key={title} variant="glass"><CardIcon className="size-6 text-[var(--brand)]"/><h2 className="mt-4 text-lg font-semibold">{title}</h2><p className="mt-2 text-slate-500">{description}</p><Button variant="ghost" className="mt-4 min-h-11 rounded-full" onClick={() => router.push(path)}>Ouvrir<ArrowRight/></Button></Surface>)}</div>
  </div>;
}

export function SheetCatalog({ catalog }: { catalog: Catalog }) {
  const router = useRouter(), [filter, setFilter] = useState('');
  const query = filter.toLocaleLowerCase('fr');
  const visible = catalog.sheets.filter(sheet => `${sheet.label} ${sheet.name} ${sheet.purpose}`.toLocaleLowerCase('fr').includes(query));
  return <div className="mt-6 space-y-5"><label className="block max-w-xl text-sm font-medium">Rechercher une feuille<input className={inputClass} value={filter} placeholder="Revenus, équipe, financement…" onChange={e => setFilter(e.target.value)}/></label>{catalog.groups.map(group => { const sheets = visible.filter(sheet => sheet.group_id === group.id); return !sheets.length ? null : <Surface key={group.id} variant="glass"><h2 className="text-xl font-semibold">{group.label}<span className="ml-3 text-sm font-normal text-slate-500">{sheets.length} feuille(s)</span></h2><div className="mt-4 grid gap-3 md:grid-cols-2">{sheets.map(sheet => <button key={sheet.id} className="flex min-h-24 items-start gap-3 rounded-2xl border border-white bg-white/75 p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:bg-white focus-visible:outline-2 focus-visible:outline-[var(--brand)]" onClick={() => router.push(sheetHref(sheet.id))}><FileSpreadsheet className="mt-1 size-5 shrink-0 text-[var(--brand)]"/><span><strong className="block text-base">{sheet.label}</strong><span className="mt-1 block text-sm leading-6 text-slate-500">{sheet.purpose || sheet.role}</span><small className="mt-2 block text-slate-400">{sheet.name} · {sheet.field_count} champs</small></span><ArrowRight className="ml-auto mt-1 size-4 shrink-0"/></button>)}</div></Surface>; })}{!visible.length && <Surface><p>Aucune feuille ne correspond à cette recherche.</p></Surface>}</div>;
}

export function ThemePage({ app, catalog, theme, version, discuss }: { app: ConnectedProps; catalog: Catalog; theme: { slug: string; id: string; label: string; description: string }; version: string; discuss: (sheet: string) => void }) {
  const router = useRouter(), params = useSearchParams();
  const sheets = catalog.sheets.filter(sheet => sheet.theme_ids.includes(theme.id));
  const selected = sheets.find(sheet => sheet.id === params.get('feuille')) || sheets.find(sheet => sheet.register?.can_add) || sheets[0];
  return <div className="space-y-6"><PageHeading eyebrow="Votre parcours" title={theme.label} description={theme.description}/><Surface variant="glass"><h2 className="text-lg font-semibold">Les feuilles de ce thème</h2><div className="mt-4 flex flex-wrap gap-2">{sheets.map(sheet => <Button key={sheet.id} variant={sheet.id === selected?.id ? 'default' : 'outline'} className="min-h-11 rounded-full px-5" aria-pressed={sheet.id === selected?.id} onClick={() => router.push('/travail/' + theme.slug + '?feuille=' + encodeURIComponent(sheet.id))}>{sheet.label}</Button>)}</div></Surface>{selected ? <SheetPanel key={app.caseId + selected.id} app={app} sheet={selected} catalog={catalog} version={version} discuss={discuss}/> : <Surface><p>Ce modèle ne comporte pas de feuille rattachée à ce thème.</p><Button className="mt-4" onClick={() => router.push('/expert')}>Consulter le modèle du dossier</Button></Surface>}</div>;
}

type Simulation = { id: string; name: string; case_id: string; status: string; stage?: string; base_revision: number; scenario_case_id?: string; saved: boolean; stale: boolean; metrics?: Metric[]; series?: FinancialSeries[]; error?: string; created_at?: string; updated_at?: string };
type Impacts = { case_id: string; revision: number; draft_id?: string; draft_fingerprint: string; status: string; changes: unknown[]; operations: { type: string; sheet?: string; cell?: string; value?: unknown; reason?: string; evidence_id?: string }[]; sources: { id: string; title: string; sha256: string }[]; affected_sheets: { id: string; name: string; label: string }[]; conflicts: unknown[]; can_simulate: boolean; blocking_reasons: string[] };
export function Scenarios({ app, workshop }: { app: ConnectedProps; workshop: ReactNode }) {
  const router = useRouter(), [name, setName] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [tick, setTick] = useState(0);
  const version = `${app.refresh}:${tick}:${app.draft.id}:${JSON.stringify(app.draft.operations || [])}`;
  const impacts = useCaseData<Impacts>(app.caseId, '/cockpit/draft/impacts', version);
  const simulations = useCaseData<{ simulations: Simulation[] }>(app.caseId, '/cockpit/simulations', app.refresh + tick);
  useEffect(() => {
    if (!simulations.data?.simulations.some(item => ['QUEUED', 'RUNNING'].includes(item.status))) return;
    const timer = window.setTimeout(() => simulations.retry(), 2000); return () => clearTimeout(timer);
  }, [simulations.data]);
  async function simulate(event: FormEvent) {
    event.preventDefault(); if (!impacts.data?.can_simulate || !name.trim() || busy || app.blocked) return;
    setBusy(true); setError('');
    try { await intentApi(app.caseId, '/cockpit/simulations', 'POST', { expected_revision: impacts.data.revision, draft_id: impacts.data.draft_id, draft_fingerprint: impacts.data.draft_fingerprint, name: name.trim() }); setName(''); setTick(n => n + 1); await app.onRefresh(); }
    catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  return <div className="space-y-6"><PageHeading eyebrow="Simulations" title="Testez une décision avant de l’adopter" description="Le brouillon est simulé sur une copie. La référence reste intacte jusqu’à votre approbation d’un nouvel aperçu."/><Surface variant="tinted"><h2 className="text-xl font-semibold">Votre prochaine simulation</h2><ReadError message={impacts.error} retry={impacts.retry}/>{impacts.loading && !impacts.data && <p role="status" className="mt-4">Lecture du brouillon et de ses sources…</p>}{impacts.data && <><div className="mt-4 flex flex-wrap gap-2"><StateBadge>{impacts.data.operations.length} opération(s)</StateBadge><StateBadge tone="neutral">Révision {impacts.data.revision}</StateBadge>{impacts.data.affected_sheets.map(sheet => <StateBadge key={sheet.id}>{sheet.label}</StateBadge>)}</div><details className="mt-4 rounded-2xl bg-white/65 p-4"><summary className="cursor-pointer font-medium">Examiner les modifications directes et leurs sources</summary><ul className="mt-3 space-y-3">{impacts.data.operations.map((operation, index) => <li key={index} className="border-t border-slate-200/60 pt-3"><strong>{operation.sheet} {operation.cell} · {statusLabel(operation.type)}</strong><p>{textValue(operation.value)}</p><p className="text-sm text-slate-500">{operation.reason || 'Justification dans le brouillon'} · {impacts.data?.sources.find(source => source.id === operation.evidence_id)?.title || 'Source à examiner dans le lot'}</p></li>)}</ul><Button variant="outline" className="mt-4 min-h-11 rounded-full" onClick={app.onDraft}>Ouvrir le lot complet avant / après</Button></details>{!!impacts.data.blocking_reasons.length && <ul className="mt-4 list-disc rounded-2xl bg-amber-50 p-5 pl-9 text-sm text-amber-900">{impacts.data.blocking_reasons.map((reason, i) => <li key={i}>{reason}</li>)}</ul>}<form onSubmit={event => void simulate(event)} className="mt-5 flex flex-wrap items-end gap-3"><label className="min-w-48 flex-1 text-sm font-medium">Nom de la simulation<input className={inputClass} required value={name} onChange={e => setName(e.target.value)} placeholder="Recrutement en janvier, nouvelle offre…"/></label><Button type="submit" className="min-h-12 rounded-full px-6" disabled={!name.trim() || !impacts.data.can_simulate || busy || app.blocked}>Simuler sur une copie<ArrowRight/></Button></form></>}{error && <p role="alert" className="mt-4 text-red-800">{error}</p>}</Surface>
    <ReadError message={simulations.error} retry={simulations.retry}/><div className="grid gap-4 md:grid-cols-2">{simulations.data?.simulations.map(item => <Surface key={item.id} variant="glass"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="text-xl font-semibold">{item.name}</h2><StateBadge tone={item.status === 'READY' ? 'success' : item.status === 'FAILED' ? 'danger' : 'warning'}>{statusLabel(item.status)}</StateBadge></div><p className="mt-3 text-sm text-slate-500">Référence : révision {item.base_revision} · {date(item.created_at)}</p>{item.stale && <p className="mt-2 text-sm text-amber-800">La référence a évolué depuis cette simulation.</p>}{item.error && <p className="mt-2 text-sm text-red-800">{item.error}</p>}<Button className="mt-5 min-h-11 rounded-full px-5" onClick={() => router.push('/simulations/' + encodeURIComponent(item.id))}>Examiner cette simulation<ArrowRight/></Button></Surface>)}</div>
    {!simulations.loading && !simulations.error && !simulations.data?.simulations.length && <Surface><p className="text-slate-500">Préparez des hypothèses dans un thème ou dans la grille, puis simulez le brouillon.</p><Button variant="outline" className="mt-4 min-h-11 rounded-full px-5" onClick={() => router.push('/parcours')}>Construire les hypothèses</Button></Surface>}
    <details className="rounded-[24px] bg-white/60 p-4"><summary className="cursor-pointer text-lg font-semibold">Scénarios libres, financement, dilution, objectifs et sensibilités</summary>{workshop}</details>
  </div>;
}

export function ScenarioDetail({ app, scenarioId }: { app: ConnectedProps; scenarioId: string }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [tick, setTick] = useState(0);
  const remote = useCaseData<Simulation>(app.caseId, '/cockpit/simulations/' + encodeURIComponent(scenarioId), app.refresh + tick);
  const reference = useCaseData<Comparison>(app.caseId, '/scenarios/compare', app.refresh);
  const item = remote.data, current = reference.data?.scenarios?.find(s => s.case_id === app.caseId || s.id === app.caseId);
  useEffect(() => { if (!item || !['QUEUED', 'RUNNING'].includes(item.status)) return; const timer = window.setTimeout(() => remote.retry(), 2000); return () => clearTimeout(timer); }, [item]);
  async function command(action: 'keep' | 'propose-adoption') {
    if (!item || busy || app.blocked || item.status !== 'READY') return; setBusy(true); setError(''); setNotice('');
    try { await intentApi(app.caseId, '/cockpit/simulations/' + encodeURIComponent(scenarioId) + '/' + action, 'POST', { expected_revision: app.active?.revision ?? 0 }); setTick(n => n + 1); await app.onRefresh(); if (action === 'propose-adoption') app.onDraft(); else setNotice('Cette simulation est conservée avec ses sources et sa copie.'); }
    catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  return <div className="space-y-6"><Button variant="ghost" className="min-h-11 rounded-full" onClick={() => router.push('/simulations')}>Toutes les simulations</Button><PageHeading eyebrow="Comparer une décision" title={item?.name || 'Simulation du dossier'} description="Les indicateurs affichés proviennent des résultats qualifiés enregistrés par le moteur. Toute adoption nécessite un aperçu et votre accord."/><ReadError message={remote.error} retry={remote.retry}/><ReadError message={reference.error} retry={reference.retry}/>{remote.loading && !item && <p role="status">Lecture de la simulation…</p>}{item && <><div className="flex flex-wrap gap-2"><StateBadge tone={item.status === 'READY' ? 'success' : 'warning'}>{statusLabel(item.status)}</StateBadge><StateBadge tone="neutral">Référence : révision {item.base_revision}</StateBadge>{item.saved && <StateBadge>Conservée</StateBadge>}{item.stale && <StateBadge tone="warning">Référence modifiée depuis le calcul</StateBadge>}</div>{item.error && <Surface><p role="alert" className="text-red-800">{item.error}</p><Button className="mt-4 min-h-11 rounded-full" onClick={app.onJobs}>Examiner ou reprendre la tâche</Button></Surface>}{item.status === 'READY' && <><Surface><h2 className="text-xl font-semibold">Référence actuelle et simulation</h2><p className="mt-2 text-sm text-slate-500">Comparer les périodes indiquées. La référence affichée est la version actuelle du dossier ; elle peut différer de celle au départ de la simulation.</p><div className="mt-5 overflow-auto"><table className="w-full min-w-[540px] text-left text-sm"><thead><tr><th className="p-3">Indicateur / période</th><th className="p-3">Référence actuelle</th><th className="p-3">Simulation</th><th className="p-3">État</th></tr></thead><tbody>{(item.metrics || []).map(metric => { const baseline = current?.metrics?.find(value => value.id === metric.id && value.period === metric.period); return <tr key={metric.id} className="border-t"><th className="p-3 font-medium">{metric.label}<small className="block font-normal text-slate-500">{metric.period} {metric.unit}</small></th><td className="p-3">{textValue(baseline?.value)}</td><td className="p-3">{textValue(metric.value)}</td><td className="p-3 text-slate-500">{statusLabel(metric.status)}</td></tr>; })}</tbody></table></div></Surface><Surface><CashComparison simulation={item.series?.find(series => series.id === 'cash')} reference={current?.series?.find(series => series.id === 'cash')}/></Surface></>}
      <Surface variant="tinted" className="sticky bottom-3 z-10"><div className="flex flex-wrap items-center justify-between gap-4"><p className="max-w-lg text-sm leading-6 text-slate-600">Conserver garde la simulation. Préparer l’adoption propose ses changements dans le brouillon de la référence ; vous examinez ensuite l’aperçu avant application.</p><div className="flex flex-wrap gap-2"><Button variant="outline" className="min-h-11 rounded-full px-5" disabled={busy || app.blocked || item.status !== 'READY' || item.saved} onClick={() => void command('keep')}>Conserver le scénario</Button><Button className="min-h-11 rounded-full px-5" disabled={busy || app.blocked || item.status !== 'READY' || item.stale} onClick={() => void command('propose-adoption')}>Préparer l’adoption</Button></div></div>{error && <p role="alert" className="mt-4 text-red-800">{error}</p>}{notice && <p role="status" className="mt-4 text-emerald-800">{notice}</p>}</Surface></>}</div>;
}

export function Decisions({ app }: { app: ConnectedProps }) {
  const remote = useCaseData<{ versions: Version[] }>(app.caseId, '/versions', app.refresh);
  const events = Array.isArray(app.active?.history) ? app.active.history as { kind?: string; created_at?: string; details?: unknown }[] : [];
  return <div className="space-y-6"><PageHeading eyebrow="Décisions" title="Gardez la trace de vos choix" description="Le brouillon, les tâches et les révisions vous permettent de comprendre ce qui a été proposé, calculé et adopté."/><div className="grid gap-4 md:grid-cols-2"><Surface variant="tinted"><Target className="size-6 text-[var(--brand)]"/><h2 className="mt-4 text-xl font-semibold">Décisions en préparation</h2><p className="mt-3 text-slate-500">{app.draft.operations?.length || 0} modification(s) dans le brouillon · {statusLabel(app.draft.status)}</p>{!!app.draft.conflicts?.length && <p className="mt-2 text-amber-800">{app.draft.conflicts.length} conflit(s) à résoudre.</p>}<Button className="mt-5 min-h-11 rounded-full px-5" onClick={app.onDraft}>Examiner le brouillon</Button></Surface><Surface variant="glass"><History className="size-6 text-[var(--brand)]"/><h2 className="mt-4 text-xl font-semibold">Calculs et traitements</h2><p className="mt-3 text-slate-500">Consultez la progression, les erreurs et les possibilités de reprise.</p><Button variant="outline" className="mt-5 min-h-11 rounded-full px-5" onClick={app.onJobs}>Ouvrir les tâches ({app.jobs.length})</Button></Surface></div><ReadError message={remote.error} retry={remote.retry}/><Surface><h2 className="text-xl font-semibold">Versions récupérables</h2><p className="mt-2 text-slate-500">Une restauration crée une nouvelle révision et conserve les précédentes.</p><div className="mt-5 space-y-3">{remote.data?.versions.map(version => <div key={version.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><span><strong>Révision {version.revision ?? '—'}</strong><small className="mt-1 block text-slate-500">{statusLabel(version.kind)} · {date(version.created_at)}</small></span>{version.current && <StateBadge>Version courante</StateBadge>}</div>)}</div><Button variant="outline" className="mt-5 min-h-11 rounded-full px-5" onClick={app.onVersions}>Consulter et restaurer une version</Button></Surface>{!!events.length && <Surface><h2 className="text-xl font-semibold">Journal du dossier</h2><div className="mt-4 space-y-3">{events.map((event, index) => <details key={index} className="rounded-2xl bg-slate-50 p-4"><summary className="cursor-pointer font-medium">{statusLabel(event.kind)} · {date(event.created_at)}</summary><p className="mt-3 break-words text-sm leading-6 text-slate-500">{textValue(event.details)}</p></details>)}</div></Surface>}</div>;
}
