/** Explicit demonstration fixtures. None of these values are financial calculations. */
export type WorkTheme = 'sales' | 'margin' | 'people' | 'investment' | 'cash' | 'summary';
export type SheetView = { id: string; excel: string; title: string; description: string; group: number; theme: WorkTheme; kind: 'help' | 'settings' | 'register' | 'series' | 'statement' | 'controls' | 'comparison'; editable: boolean; rows: [string, string, string][]; dependencies: string[] };
const definitions: Array<[string,string,string,string,number,WorkTheme,SheetView['kind'],boolean,string[]]> = [
 ['legend','Légende','Lire le modèle','Conventions, couleurs, unités et distinction entre hypothèse et résultat.',0,'summary','help',false,['control','checks']],
 ['overview','Previsionnel','Le dossier et son horizon','Présentation du périmètre de la trajectoire.',0,'summary','help',false,['control','assumptions']],
 ['control','Control','Calendrier du dossier','Calendrier civil et démarrage de l’activité.',0,'summary','settings',true,['overview','financial-model']],
 ['assumptions','Assumptions','Hypothèses et offres','Paramètres partagés entre les contrats et activités.',0,'sales','settings',true,['contracts-data','working-capital']],
 ['contracts-data','DATA Contrats','Contrats commerciaux','Fiches, conditions, sources et échéances des contrats.',1,'sales','register',true,['contracts','revenue']],
 ['contracts','Contrats','Calendrier des contrats','Répartition des prestations selon leurs dates et leur reconnaissance.',1,'sales','series',false,['contracts-data','revenue']],
 ['revenue','Revenue','Revenu, facturation et encaissement','Trois flux distincts ; chaque série doit avoir sa propre origine.',1,'sales','series',false,['contracts-data','working-capital','cashflow']],
 ['purchases-data','DATA COGS','Achats et composants','Quantités et coût unitaire des composants.',2,'margin','register',true,['cogs','stock']],
 ['cogs','COGS','Coûts directs et marge','Coûts affectés à la production et contribution à la marge.',2,'margin','series',false,['purchases-data','income']],
 ['stock','Stock','Stocks et couverture','Politique de stockage, besoins et consommation.',2,'margin','settings',true,['purchases-data','working-capital']],
 ['expenses','Charges_Externes','Charges d’exploitation','Postes récurrents et ponctuels, dates et pièces.',2,'margin','register',true,['income','cashflow']],
 ['people','Effectifs','Équipe et recrutements','Postes, salaire et calendrier des entrées.',2,'people','register',true,['tax-credit','income','cashflow']],
 ['capex-data','DATA CAPEX','Investissements','Fiches d’équipements et dates de mise en service.',3,'investment','register',true,['capex','debt']],
 ['capex','CAPEX','Investissements et amortissements','Décaissement et amortissement suivent deux calendriers.',3,'investment','series',false,['capex-data','balance']],
 ['debt','Financement Dette','Dette et remboursements','Conditions d’emprunt et échéancier.',3,'investment','register',true,['funding-data','cashflow']],
 ['funding-data','DATA Financement','Opérations de financement','Apports, dates et sources des financements.',3,'investment','register',true,['funding','financing-plan']],
 ['funding','Financement E&S','Fonds propres et subventions','Ressources de financement et calendrier.',3,'investment','series',false,['funding-data','grant']],
 ['grant','SUBVENTION_INVEST','Subventions d’investissement','Dépense éligible, aide et dates attendues.',3,'investment','register',true,['capex-data','funding']],
 ['tax-credit','CALCUL_CIR','Crédit d’impôt : hypothèses','Assiette et qualification documentée, séparées du résultat.',4,'people','settings',true,['people','tax-workshop']],
 ['tax-workshop','ATELIER_CIR_IS','Atelier fiscal','Hypothèses fiscales et confirmations applicables.',4,'cash','settings',true,['tax-credit','cashflow','checks']],
 ['working-capital','BFR','Besoin d’exploitation','Délais, stock et besoins temporaires de trésorerie.',4,'cash','series',false,['assumptions','stock','cashflow']],
 ['financial-model','Modèle financier','Trajectoire consolidée','États financiers consolidés et facteurs explicatifs.',5,'summary','statement',false,['income','balance','cashflow']],
 ['income','Compte de Résultat','Compte de résultat','Activité, coûts et résultat sur la période.',5,'summary','statement',false,['revenue','cogs','people']],
 ['balance','Bilan','Bilan','Actif, passif et équilibre à une date donnée.',5,'summary','statement',false,['stock','capex','funding']],
 ['cashflow','Flux de trésorerie','Trésorerie mensuelle','Flux et solde mensuel, distincts du résultat comptable.',5,'cash','series',false,['revenue','working-capital','debt']],
 ['financing-plan','Plan de financement','Besoins et ressources','Équilibre des besoins et ressources de financement.',5,'investment','statement',false,['capex-data','debt','funding']],
 ['sensitivity-inputs','Sensi TCA','Sensibilités : hypothèses','Variations préparées dans une copie de scénario.',6,'summary','comparison',true,['sensitivity-results','sensitivity-charts']],
 ['sensitivity-results','Sensi Analyses','Comparer les sensibilités','Comparer les résultats des cas explicitement préparés.',6,'summary','comparison',false,['sensitivity-inputs','sensitivity-charts']],
 ['sensitivity-charts','Sensi Graphiques','Visualiser les sensibilités','Lire les variantes puis ouvrir leur origine.',6,'summary','comparison',false,['sensitivity-results','valuation']],
 ['valuation','Valorisation','Hypothèses de valeur','Valeur indicative et hypothèses ; résultat protégé.',6,'summary','comparison',true,['comparables','financial-model']],
 ['comparables','Comparables','Comparables','Échantillon de sociétés et multiples documentés.',6,'summary','register',true,['valuation']],
 ['dashboard','KPI Dashboard','Indicateurs','Indicateurs et périodes de référence.',7,'summary','statement',false,['income','cashflow','valuation']],
 ['checks','Contrôles','Comprendre les contrôles','Questions, incohérences et données à confirmer.',7,'summary','controls',false,['control','contracts-data','tax-workshop']],
];
const examples: Record<string,[string,string,string][]> = {
 legend:[['Entrée','Hypothèse modifiable','Source à confirmer'],['Résultat','Lecture seule','Fixture illustrative'],['Unité','EUR / % / mois','Affichée avec chaque donnée']],
 overview:[['Entreprise','Luméo Systems','Dossier fictif'],['Horizon','2026–2028','Janvier–décembre'],['Objet','Préparer une décision','Aucun fichier réel lu']],
 control:[['Première année','2026','Paramètre'],['Horizon','3 ans','Paramètre'],['Démarrage','01/10/2026','Hypothèse fictive']],
 assumptions:[['Offre','Inspection industrielle','Forfait'],['Délai client','60 jours','Partagé par offre'],['TVA','20 %','Hypothèse fictive, à qualifier']],
 'contracts-data':[['Atlas Mobility','480 000 EUR','Probable'],['Offre','Inspection industrielle','Forfait'],['Source','Contrat Atlas fictif','À confirmer']],
 contracts:[['Début','01/10/2026','Contrat Atlas'],['Fin','31/01/2027','Quatre mois'],['Reconnaissance','25 % par mois','Fixture de calendrier']],
 revenue:[['Revenu reconnu','À consulter dans le cas sélectionné','Reconnaissance'],['Facturation','Échéancier à qualifier','Ne pas confondre avec le revenu'],['Encaissement','Délai partagé de l’offre','Aucun flux comptable réel']],
 'purchases-data':[['Composant optique','120 EUR / unité','Tarif fictif'],['Quantité','200 unités','Commande de démonstration'],['Source','Devis fournisseur fictif','À confirmer']],
 cogs:[['Achats du composant','24 000 EUR','Cas de référence préparé'],['Variante tarif 130 EUR','26 000 EUR','Cas alternatif préparé'],['Impact','Marge et trésorerie','Résultat protégé']],
 stock:[['Couverture','6 semaines','Hypothèse'],['Article','Composant optique','Stock fictif'],['Lien','Coût d’achat','Même brouillon que la fiche']],
 expenses:[['Loyer','2 000 EUR / mois','Exemple fictif'],['Logiciels','500 EUR / mois','Exemple fictif'],['Calendrier','Janvier–décembre 2026','Postes distincts des achats']],
 people:[['Poste','Ingénieur production','Un recrutement fictif'],['Salaire annuel brut','60 000 EUR','Source fictive'],['Début','01/10/2026','Variante : janvier 2027']],
 'capex-data':[['Équipement','Banc de test','Exemple fictif'],['Montant','60 000 EUR','Hors taxes'],['Mise en service','Octobre 2026','Variante : janvier 2027']],
 capex:[['Décaissement','60 000 EUR','Cas préparé'],['Durée','5 ans','Hypothèse fictive'],['Amortissement','Selon mise en service','Résultat protégé']],
 debt:[['Emprunt','40 000 EUR','Exemple fictif'],['Durée','36 mois','Conditions à confirmer'],['Taux','5 %','Taux fictif']],
 'funding-data':[['Apport','20 000 EUR','Exemple fictif'],['Dette','40 000 EUR','Exemple fictif'],['Date','01/10/2026','Conditions à confirmer']],
 funding:[['Fonds propres','20 000 EUR','Cas préparé'],['Aide','Non confirmée','Pas de zéro implicite'],['Origine','Registre financement','Résultat protégé']],
 grant:[['Dispositif','Aide équipement (fictive)','Hypothèse'],['Montant','À confirmer','Information manquante'],['Notification','Non reçue','Ne constitue pas un droit acquis']],
 'tax-credit':[['Personnel éligible','À qualifier','Aucun droit fiscal affirmé'],['Période','2026','Exemple'],['Source','Justificatif à compléter','Résultat indisponible']],
 'tax-workshop':[['Juridiction','À confirmer','Qualification nécessaire'],['Crédit d’impôt','À compléter','Non intégré à la fixture'],['Impôt','Résultat indisponible','Pas de calcul fiscal TypeScript']],
 'working-capital':[['Délai client','60 jours','Partagé par offre'],['Délai fournisseur','30 jours','Exemple fictif'],['Stock','6 semaines','Lien vers la politique']],
 'financial-model':[['Revenu','2 400 000 EUR','Fixture de référence'],['Marge brute','46 %','Fixture de référence'],['Point bas','118 000 EUR','Fixture de référence']],
 income:[['Revenu','2 400 000 EUR','Horizon fictif 2026–2028'],['Marge brute','46 %','Indicateur préparé'],['Résultat net','À calculer dans le moteur','Non fourni par la fixture']],
 balance:[['Actif','À compléter','Fixture sans bilan complet'],['Passif','À compléter','Pas de valeur inventée'],['Équilibre','Non vérifié','Nécessite le moteur']],
 cashflow:[['Point bas','118 000 EUR','Fixture de référence'],['Date','Mars 2027','Trajectoire illustrative'],['Trésorerie initiale','320 000 EUR','Situation fictive']],
 'financing-plan':[['Équipement','60 000 EUR','Besoin fictif'],['Apport','20 000 EUR','Ressource fictive'],['Dette','40 000 EUR','Ressource fictive']],
 'sensitivity-inputs':[['Levier','Multiple de valorisation','Un cas à la fois'],['Cas de référence','4 ×','Fixture'],['Cas alternatif','5 ×','Fixture']],
 'sensitivity-results':[['Référence','4 × : 1 200 000 EUR','Exemple préparé'],['Variante','5 × : 1 500 000 EUR','Exemple préparé'],['Autres hypothèses','Identiques dans cet exemple','Aucune interpolation']],
 'sensitivity-charts':[['Référence','1 200 000 EUR','Exemple préparé'],['Variante','1 500 000 EUR','Exemple préparé'],['Source','Échantillon fictif','Non utilisable pour une décision réelle']],
 valuation:[['Méthode','Multiple illustratif','Pas une expertise'],['Base','300 000 EUR','Fixture fictive'],['Multiple','4 × ou 5 ×','Aucun WACC ajusté']],
 comparables:[['Société A (fictive)','4 ×','Échantillon illustratif'],['Société B (fictive)','5 ×','Échantillon illustratif'],['Qualification','Non représentative du marché','Aucune source externe']],
 dashboard:[['Revenu','2 400 000 EUR','Horizon fictif'],['Point bas','118 000 EUR','Mars 2027'],['Visibilité','11 mois','Valeur préparée, pas calculée']],
 checks:[['Sources','À confirmer','Ouvrir les sources'],['Statut contrat','Probable','Ne devient pas signé à 100 %'],['Calcul','Fixture illustrative','Aucun contrôle Excel réel']],
};
export const sheetViews: SheetView[] = definitions.map(([id,excel,title,description,group,theme,kind,editable,dependencies])=>({id,excel,title,description,group,theme,kind,editable,dependencies,rows:examples[id]}));
export const sheetGroups = ['Cadre du projet','Ventes et contrats','Coûts, exploitation et équipe','Investissements et financements','Fiscalité et besoin d’exploitation','Résultats et trésorerie','Scénarios et valeur','Tableau de bord et validations'];
export const sheetByName = (name:string) => sheetViews.find(s=>s.excel===(name==='Sensi Scénarios'?'Sensi TCA':name));
export const sheetHref = (id:string,view='metier')=>`/expert/feuilles/${encodeURIComponent(id)}?vue=${view}`;
export type ThemeFixture = { id:string; value:string; label:string; outputs:[string,string][]; explanation:string };
export type ThemeWorkspace = { key:Exclude<WorkTheme,'sales'>; slug:string; title:string; elementId:string; element:string; field:string; unit:string; sourceId:string; sourceValue:string; sheets:string[]; fixtures:ThemeFixture[] };
export const themeWorkspaces:ThemeWorkspace[] = [
 {key:'margin',slug:'couts',title:'Coûts et marge',elementId:'component-optic',element:'Composant optique',field:'Coût unitaire',unit:'EUR / unité',sourceId:'source-supplier',sourceValue:'120 EUR par composant',sheets:['purchases-data','cogs','stock','expenses'],fixtures:[{id:'cost-120',value:'120',label:'Tarif de référence',outputs:[['Achats de 200 composants','24 000 EUR'],['Écart au cas de référence','0 EUR']],explanation:'Cas préparé : commande inchangée de 200 composants.'},{id:'cost-130',value:'130',label:'Tarif révisé',outputs:[['Achats de 200 composants','26 000 EUR'],['Surcoût illustratif','2 000 EUR']],explanation:'Le surcoût réduit la marge et augmente le décaissement ; calendrier identique dans cette fixture.'}]},
 {key:'people',slug:'equipe',title:'Équipe',elementId:'hire-engineer',element:'Recrutement ingénieur',field:'Date d’entrée',unit:'date',sourceId:'source-hiring',sourceValue:'Entrée prévue octobre 2026',sheets:['people','tax-credit','income'],fixtures:[{id:'hire-oct',value:'2026-10-01',label:'Entrée en octobre',outputs:[['Coût chargé octobre–décembre','21 000 EUR'],['Écart 2026','0 EUR']],explanation:'Cas préparé : 60 000 EUR brut annuel et charges de 40 %, trois mois.'},{id:'hire-jan',value:'2027-01-01',label:'Entrée en janvier',outputs:[['Coût chargé octobre–décembre','0 EUR'],['Décaissement 2026 évité','21 000 EUR']],explanation:'Le coût est décalé vers 2027 ; la capacité de production est également à revoir.'}]},
 {key:'investment',slug:'investissements',title:'Investissements et financement',elementId:'equipment-bench',element:'Banc de test',field:'Mise en service',unit:'date',sourceId:'source-equipment',sourceValue:'Banc de test de 60 000 EUR',sheets:['capex-data','capex','debt','funding-data','funding','grant'],fixtures:[{id:'capex-oct',value:'2026-10-01',label:'Équipement en octobre',outputs:[['Décaissement équipement 2026','60 000 EUR'],['Amortissement 2026 (fixture)','3 000 EUR']],explanation:'Équipement amorti sur cinq ans ; financement distinct à examiner.'},{id:'capex-jan',value:'2027-01-01',label:'Équipement en janvier',outputs:[['Décaissement équipement 2026','0 EUR'],['Amortissement 2026 (fixture)','0 EUR']],explanation:'L’achat et la mise en service passent en janvier 2027 ; les engagements de dette restent à examiner.'}]},
 {key:'cash',slug:'tresorerie',title:'Trésorerie et fiscalité',elementId:'offer-terms',element:'Délai partagé de l’offre',field:'Paiement client',unit:'jours',sourceId:'source-terms',sourceValue:'Délai client de 60 jours',sheets:['assumptions','working-capital','cashflow','tax-workshop'],fixtures:[{id:'terms-60',value:'60',label:'Délai actuel',outputs:[['Encaissement facture exemple de 10 000 EUR','Décembre 2026'],['Impôt','Non qualifié']],explanation:'Facture exemple du 1er octobre, hypothèse de règlement à 60 jours.'},{id:'terms-30',value:'30',label:'Paiement accéléré',outputs:[['Encaissement facture exemple de 10 000 EUR','Novembre 2026'],['Impôt','Non qualifié']],explanation:'Hypothèse partagée par l’offre, pas seulement par un contrat ; aucune variation fiscale calculée.'}]},
 {key:'summary',slug:'synthese',title:'Synthèse et valeur',elementId:'valuation-multiple',element:'Comparaison de multiples',field:'Multiple retenu',unit:'×',sourceId:'source-comparables',sourceValue:'Échantillon fictif : multiples 4 et 5',sheets:['financial-model','income','balance','dashboard','checks','valuation','comparables','sensitivity-inputs','sensitivity-results','sensitivity-charts'],fixtures:[{id:'value-4',value:'4',label:'Multiple de référence',outputs:[['Valeur illustrative','1 200 000 EUR'],['Base indicative','300 000 EUR']],explanation:'Exemple préparé de comparaison ; aucune conclusion sur une valeur de marché.'},{id:'value-5',value:'5',label:'Multiple alternatif',outputs:[['Valeur illustrative','1 500 000 EUR'],['Base indicative','300 000 EUR']],explanation:'Seul le multiple change dans cette fixture. Le WACC et les résultats du modèle ne sont pas modifiés.'}]},
];
export const themeRoute = (key:WorkTheme)=>key==='sales'?'/travail/ventes':`/travail/${themeWorkspaces.find(t=>t.key===key)?.slug ?? 'synthese'}`;
export type DemoSource = { id:string; caseId:string; title:string; kind:'example'|'metadata'; fileName?:string; facts:{ id:string; label:string; value:string; status:'unconfirmed'|'confirmed'|'corrected'|'removed'; themes:WorkTheme[] }[] };
export type ThemeDraft = {id:string; elementId:string; value:string; undo:string[]; status:'draft'|'previewed'|'simulated'|'applied'; scenarioId?:string; error?:string};
export type ThemeScenario = {id:string; caseId:string; theme:Exclude<WorkTheme,'sales'>; elementId:string; name:string; value:string; fixtureId:string; sourceSignature:string; baseVersionId:string; outputs:[string,string][]; status:'simulated'|'saved'|'applied'; createdAt:string};
export type ThemeVersion = {id:string; createdAt:string; reason:string; theme:Exclude<WorkTheme,'sales'>; scenarioId?:string; value:string; outputs:[string,string][]};
export type SharedDemoState = {caseId:string; activeTheme:WorkTheme; sources:DemoSource[]; themeDrafts:Record<string,ThemeDraft>; themeScenarios:ThemeScenario[]; themeVersions:ThemeVersion[]; monthlyImport?:{period:string; fileName:string; mapping:Record<string,string>; status:'mapping'|'preview'|'confirmed'}; deliverable?:{versionId:string; format:string; status:'queued'|'running'|'ready'|'failed'; error?:string}};
export function sharedInitialState():SharedDemoState { return {caseId:'demo-lumeo',activeTheme:'sales',sources:[{id:'source-atlas',caseId:'demo-lumeo',title:'Contrat Atlas fictif',kind:'example',facts:[{id:'fact-atlas',label:'Forfait proposé',value:'480000',status:'unconfirmed',themes:['sales']}]},...themeWorkspaces.map(t=>({id:t.sourceId,caseId:'demo-lumeo',title:`Source fictive : ${t.element}`,kind:'example' as const,facts:[{id:`fact-${t.key}`,label:t.field,value:t.sourceValue,status:'unconfirmed' as const,themes:[t.key]}]}))],themeDrafts:Object.fromEntries(themeWorkspaces.map(t=>[t.key,{id:`draft-${t.key}`,elementId:t.elementId,value:t.fixtures[0].value,undo:[],status:'draft'}])),themeScenarios:[],themeVersions:[],}; }
export function sourceSignature(state:SharedDemoState,theme:WorkTheme){return JSON.stringify(state.sources.filter(s=>s.caseId===state.caseId&&s.facts.some(f=>f.themes.includes(theme))).map(s=>({id:s.id,facts:s.facts})));}
export function sourceConfirmed(state:SharedDemoState,theme:WorkTheme){return state.sources.some(s=>s.caseId===state.caseId&&s.facts.some(f=>f.themes.includes(theme)&&f.status==='confirmed'));}
export function changeTheme(state:SharedDemoState,theme:string,value:string):SharedDemoState {const d=state.themeDrafts[theme]; if(!d || d.value===value)return state; return {...state,themeDrafts:{...state.themeDrafts,[theme]:{...d,value,undo:[...d.undo,d.value],status:'draft',scenarioId:undefined,error:undefined}}};}
export function prepareTheme(state:SharedDemoState,theme:string):SharedDemoState {const definition=themeWorkspaces.find(t=>t.key===theme), d=state.themeDrafts[theme];if(!definition||!d)return state;const fixture=definition.fixtures.find(f=>f.value===d.value);const error=!fixture?'Cette combinaison ne possède pas de fixture. Choisissez un cas proposé ou utilisez le moteur connecté.':!sourceConfirmed(state,definition.key)?'Confirmez une source fictive de ce thème avant la simulation.':undefined;return {...state,activeTheme:definition.key,themeDrafts:{...state.themeDrafts,[theme]:{...d,status:error?'draft':'previewed',error}}};}
export function simulateTheme(state:SharedDemoState,theme:string,id:string,createdAt:string):SharedDemoState {const d=state.themeDrafts[theme],definition=themeWorkspaces.find(t=>t.key===theme);if(!d||!definition||d.status!=='previewed')return state;const ready=prepareTheme(state,theme);if(ready.themeDrafts[theme].error)return ready;const fixture=definition.fixtures.find(f=>f.value===d.value)!;const scenario:ThemeScenario={id,caseId:state.caseId,theme:definition.key,elementId:definition.elementId,name:`${definition.element} : ${fixture.label}`,value:d.value,fixtureId:fixture.id,sourceSignature:sourceSignature(state,definition.key),baseVersionId:state.themeVersions.find(v=>v.theme===theme)?.id ?? `initial-${theme}`,outputs:fixture.outputs.map(r=>[...r]),status:'simulated',createdAt};return {...state,themeScenarios:[scenario,...state.themeScenarios],themeDrafts:{...state.themeDrafts,[theme]:{...d,status:'simulated',scenarioId:id}}};}
export function applyTheme(state:SharedDemoState,id:string,versionId:string,createdAt:string):SharedDemoState {const s=state.themeScenarios.find(s=>s.id===id);if(!s||s.status==='applied')return state;const d=state.themeDrafts[s.theme],currentVersion=state.themeVersions.find(v=>v.theme===s.theme)?.id ?? `initial-${s.theme}`;if(d.scenarioId!==id||d.value!==s.value||s.sourceSignature!==sourceSignature(state,s.theme)||!sourceConfirmed(state,s.theme)||s.baseVersionId!==currentVersion)return {...state,themeDrafts:{...state.themeDrafts,[s.theme]:{...d,error:'Simulation périmée : préparez puis simulez à nouveau.'}}};return {...state,themeScenarios:state.themeScenarios.map(item=>item.id===id?{...item,status:'applied'}:item),themeVersions:[{id:versionId,createdAt,reason:s.name,theme:s.theme,scenarioId:s.id,value:s.value,outputs:s.outputs.map(r=>[...r])},...state.themeVersions],themeDrafts:{...state.themeDrafts,[s.theme]:{...d,status:'applied',error:undefined}}};}
export const demoRoutePatterns=['/expert/feuilles/:sheetId',...themeWorkspaces.map(t=>`/travail/${t.slug}`),'/simulations/:scenarioId'];
export type DemoCommand =
 | {type:'theme-edit';theme:string;value:string}|{type:'theme-undo'|'theme-discard'|'theme-preview';theme:string}
 | {type:'theme-simulate';theme:string;id:string;at:string}|{type:'scenario-save'|'scenario-load';id:string}
 | {type:'scenario-apply';id:string;versionId:string;at:string}|{type:'version-restore';id:string;versionId:string;at:string}
 | {type:'source-add';source:DemoSource}|{type:'source-fact';sourceId:string;factId:string;value?:string;status:DemoSource['facts'][number]['status']}
 | {type:'active-theme';theme:WorkTheme}|{type:'monthly-start';period:string;fileName:string}
 | {type:'monthly-map';column:string;metric:string}|{type:'monthly-preview'|'monthly-confirm'}
 | {type:'deliverable';versionId:string;format:string;status:'queued'|'running'|'ready'|'failed';error?:string};
export function reduceSharedState(state:SharedDemoState,command:DemoCommand):SharedDemoState {
 switch(command.type){
 case 'active-theme':return {...state,activeTheme:command.theme};
 case 'theme-edit':return changeTheme(state,command.theme,command.value);
 case 'theme-preview':return prepareTheme(state,command.theme);
 case 'theme-undo':{const d=state.themeDrafts[command.theme];if(!d?.undo.length)return state;return {...state,themeDrafts:{...state.themeDrafts,[command.theme]:{...d,value:d.undo.at(-1)!,undo:d.undo.slice(0,-1),status:'draft',scenarioId:undefined,error:undefined}}};}
 case 'theme-discard':{const d=state.themeDrafts[command.theme],definition=themeWorkspaces.find(t=>t.key===command.theme);if(!d||!definition)return state;return changeTheme(state,command.theme,state.themeVersions.find(v=>v.theme===command.theme)?.value ?? definition.fixtures[0].value);}
 case 'theme-simulate':return simulateTheme(state,command.theme,command.id,command.at);
 case 'scenario-save':return {...state,themeScenarios:state.themeScenarios.map(s=>s.id===command.id&&s.status==='simulated'?{...s,status:'saved'}:s)};
 case 'scenario-load':{const s=state.themeScenarios.find(s=>s.id===command.id);if(!s)return state;const d=state.themeDrafts[s.theme];const fresh=s.sourceSignature===sourceSignature(state,s.theme);return {...state,activeTheme:s.theme,themeDrafts:{...state.themeDrafts,[s.theme]:{...d,value:s.value,undo:[...d.undo,d.value],status:fresh?'simulated':'draft',scenarioId:fresh?s.id:undefined,error:fresh?undefined:'Sources modifiées : une nouvelle simulation est nécessaire.'}}};}
 case 'scenario-apply':return applyTheme(state,command.id,command.versionId,command.at);
 case 'version-restore':{const v=state.themeVersions.find(v=>v.id===command.id);if(!v)return state;const d=state.themeDrafts[v.theme];return {...state,themeVersions:[{...v,id:command.versionId,createdAt:command.at,reason:`Restauration : ${v.reason}`},...state.themeVersions],themeDrafts:{...state.themeDrafts,[v.theme]:{...d,value:v.value,undo:[...d.undo,d.value],status:'draft',scenarioId:undefined}}};}
 case 'source-add':return command.source.caseId!==state.caseId||state.sources.some(s=>s.id===command.source.id)?state:{...state,sources:[...state.sources,command.source]};
 case 'source-fact':{const source=state.sources.find(s=>s.id===command.sourceId),fact=source?.facts.find(f=>f.id===command.factId);if(!fact||source?.caseId!==state.caseId||(fact.status===command.status&&(command.value===undefined||command.value===fact.value)))return state;return {...state,sources:state.sources.map(s=>s.id===source!.id?{...s,facts:s.facts.map(f=>f.id===fact.id?{...f,value:command.value ?? f.value,status:command.status}:f)}:s),themeDrafts:Object.fromEntries(Object.entries(state.themeDrafts).map(([theme,d])=>[theme,fact.themes.includes(theme as WorkTheme)?{...d,status:'draft',scenarioId:undefined,error:'La source a changé. Examinez à nouveau les impacts.'}:d]))};}
 case 'monthly-start':return {...state,monthlyImport:{period:command.period,fileName:command.fileName,mapping:{},status:'mapping'}};
 case 'monthly-map':return state.monthlyImport?{...state,monthlyImport:{...state.monthlyImport,mapping:{...state.monthlyImport.mapping,[command.column]:command.metric},status:'mapping'}}:state;
 case 'monthly-preview':{const m=state.monthlyImport;if(!m||m.period!=='2026-08'||m.mapping.encaissements!=='cash_receipts'||m.mapping.achats!=='purchases')return state;return {...state,monthlyImport:{...m,status:'preview'}};}
 case 'monthly-confirm':return state.monthlyImport?.status==='preview'?{...state,monthlyImport:{...state.monthlyImport,status:'confirmed'}}:state;
 case 'deliverable':return {...state,deliverable:{versionId:command.versionId,format:command.format,status:command.status,error:command.error}};
 }
}
