import { useState } from 'react';
import Link from 'next/link';
import { useDemo } from '@/components/cockpit/demo-provider';
import { Button } from '@/components/ui/button';
import { Surface, StateBadge } from '@/components/cockpit/page-elements';
import { sheetHref, sheetViews, themeRoute, themeWorkspaces, type WorkTheme } from '@/lib/catalog';

export function SheetLinks({ ids }: { ids:string[] }) {return <nav aria-label="Feuilles associées" className="flex flex-wrap gap-3">{ids.map(id=>{const s=sheetViews.find(s=>s.id===id);return s?<Link className="liquid-control rounded-2xl px-4 py-3 underline" key={id} href={sheetHref(id)}>{s.title}</Link>:null;})}</nav>;}
export function SourcesPanel({theme}:{theme?:WorkTheme}) {const {state,command}=useDemo();return <section className="space-y-4" aria-label="Sources de démonstration"><p className="text-slate-600">Sources fictives conservées sur cet appareil. Les fichiers financiers sélectionnés ne sont jamais analysés en mode démo.</p>{state.sources.filter(s=>!theme||s.facts.some(f=>f.themes.includes(theme))).map(source=><Surface key={source.id}><h3 className="font-semibold">{source.title}</h3><p>{source.kind==='metadata'?'Métadonnées seulement, contenu non lu':'Exemple préparé'} · {source.id}</p>{source.facts.map(fact=><Fact key={fact.id} sourceId={source.id} fact={fact}/>)}{!source.facts.length&&<p>Aucun fait extrait : document non analysé.</p>}</Surface>)}</section>;}
function Fact({sourceId,fact}:{sourceId:string;fact:ReturnType<typeof useDemo>['state']['sources'][number]['facts'][number]}) {const {command}=useDemo();const [value,setValue]=useState(fact.value);return <div className="mt-4 space-y-3 border-t pt-4"><label className="block">{fact.label}<input className="mt-2 block w-full rounded-xl border bg-white p-3" value={value} onChange={e=>setValue(e.target.value)}/></label><StateBadge tone={fact.status==='confirmed'?'success':'warning'}>{({confirmed:'Confirmé (exemple)',unconfirmed:'À confirmer',corrected:'Corrigé, à confirmer',removed:'Retiré'})[fact.status]}</StateBadge><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>command({type:'source-fact',sourceId,factId:fact.id,value,status:'corrected'})}>Corriger le fait</Button><Button disabled={value!==fact.value||fact.status==='removed'} onClick={()=>command({type:'source-fact',sourceId,factId:fact.id,status:'confirmed'})}>Confirmer l’exemple</Button><Button variant="ghost" onClick={()=>command({type:'source-fact',sourceId,factId:fact.id,status:'removed'})}>Retirer le fait</Button></div><div className="flex flex-wrap gap-3">{fact.themes.map(theme=><Link key={theme} className="underline" href={themeRoute(theme)}>Rejoindre {theme==='sales'?'Ventes':themeWorkspaces.find(t=>t.key===theme)?.title}</Link>)}</div></div>;}
export function ThemeJourneys(){const {state}=useDemo();return <section className="space-y-4"><h2 className="text-xl font-semibold">Les autres décisions à préparer</h2><div className="grid gap-4 lg:grid-cols-2">{themeWorkspaces.map(theme=>{const d=state.themeDrafts[theme.key],last=state.themeVersions.find(v=>v.theme===theme.key);return <Surface key={theme.key} variant="floating"><h3 className="font-semibold">{theme.title}</h3><p className="mt-2">{last?`Dernière décision : ${last.reason}`:theme.element}</p><p className="mt-2">{d.status==='draft'?'Brouillon à examiner':d.status==='previewed'?'Impacts préparés':d.status==='applied'?'Version locale adoptée':'Simulation disponible'}</p><Link className="mt-4 inline-block rounded-full bg-[var(--brand-deep)] px-5 py-3 text-white" href={themeRoute(theme.key)}>Continuer ce thème</Link></Surface>;})}</div></section>;}
