import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const root=new URL('../src/cockpit/',import.meta.url);
function compile(file,deps={}) {const source=fs.readFileSync(new URL(file,root),'utf8'),exports={};const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{exports,require:id=>{if(!(id in deps))throw Error(id);return deps[id];}});return exports;}
const catalog=compile('lib/catalog.ts'),model=compile('lib/demo.ts',{'./catalog':catalog});
const plain=value=>JSON.parse(JSON.stringify(value));
const send=(state,command)=>catalog.reduceSharedState(state,command);
function confirm(state,key){const source=state.sources.find(s=>s.facts.some(f=>f.themes.includes(key)));return send(state,{type:'source-fact',sourceId:source.id,factId:source.facts[0].id,status:'confirmed'});}
test('33 unique stable sheet destinations, exact Excel names, every dependency resolves',()=>{const ids=new Set(catalog.sheetViews.map(s=>s.id));assert.equal(ids.size,33);assert.equal(new Set(catalog.sheetViews.map(s=>s.excel)).size,33);for(const s of catalog.sheetViews){assert.ok(s.rows.length);for(const dep of s.dependencies)assert.ok(ids.has(dep),`${s.id} -> ${dep}`);}assert.equal(catalog.sheetByName('Sensi Scénarios').excel,'Sensi TCA');});
test('v1 migration preserves company, palette, logo, edits, all variants and historical figures',()=>{const old=plain(model.createInitialState());old.schemaVersion=1;old.brand.firstName='Camille';old.brand.logoDataUrl='data:image/png;base64,example';old.savedVariants=Array.from({length:5},(_,i)=>({id:'old-'+i,name:'Variante '+i,createdAt:'hier',inputs:{...old.contract,amount:500000+i},metrics:{...old.referenceMetrics,revenue:1+i}}));old.customExtension={keep:true};delete old.themeDrafts;delete old.themeVersions;delete old.themeScenarios;delete old.sources;const before=JSON.stringify(old);const restored=model.migrateDemoState(before);assert.equal(restored.schemaVersion,2);for(const key of ['brand','savedVariants','referenceVersions','decisions','contract','customExtension'])assert.deepEqual(plain(restored[key]),old[key]);assert.equal(JSON.stringify(old),before);assert.equal(Object.keys(restored.themeDrafts).length,5);assert.equal(restored.sources.length,6);});
test('unknown storage schema or corrupt JSON is refused',()=>{assert.equal(model.migrateDemoState('{bad'),null);assert.equal(model.migrateDemoState('{"schemaVersion":99}'),null);});
test('Atlas financial values come only from two exact fixtures, no interpolated amount or timing',()=>{const a={...model.initialContract,revenueRule:'spread'};assert.equal(model.calculateScenario(a).cashLowPoint,42000);assert.equal(model.calculateScenario({...a,depositPercent:40,paymentDays:30}).cashLowPoint,179500);for(const patch of [{amount:480001},{paymentDays:45},{deliveryMonths:3},{probability:100},{vat:10},{commercialStatus:'signed'},{startMonth:'Novembre 2026'}])assert.equal(model.scenarioFixture({...a,...patch}),undefined);assert.throws(()=>model.calculateScenario({...a,amount:480001}));assert.equal(model.cashFixtureForLowPoint(123456).length,0);});
for(const theme of catalog.themeWorkspaces)test(`${theme.key}: source -> edit -> preview -> simulate -> save -> apply once, unrelated themes unchanged`,()=>{let state=model.createInitialState();const original=plain(state);state=send(state,{type:'theme-preview',theme:theme.key});assert.match(state.themeDrafts[theme.key].error,/source/);state=confirm(state,theme.key);state=send(state,{type:'theme-edit',theme:theme.key,value:theme.fixtures[1].value});state=send(state,{type:'theme-simulate',theme:theme.key,id:'too-soon',at:'today'});assert.equal(state.themeScenarios.length,0);state=send(state,{type:'theme-preview',theme:theme.key});assert.equal(state.themeDrafts[theme.key].status,'previewed');state=send(state,{type:'theme-simulate',theme:theme.key,id:'scenario-'+theme.key,at:'today'});assert.equal(state.themeScenarios[0].fixtureId,theme.fixtures[1].id);assert.equal(state.themeVersions.length,0);state=send(state,{type:'scenario-save',id:'scenario-'+theme.key});state=send(state,{type:'scenario-apply',id:'scenario-'+theme.key,versionId:'v1',at:'today'});state=send(state,{type:'scenario-apply',id:'scenario-'+theme.key,versionId:'v2',at:'today'});assert.equal(state.themeVersions.length,1);assert.deepEqual(plain(state.themeVersions[0].outputs),plain(theme.fixtures[1].outputs));assert.deepEqual(plain(state.referenceVersions),original.referenceVersions);for(const other of catalog.themeWorkspaces.filter(t=>t.key!==theme.key))assert.deepEqual(plain(state.themeDrafts[other.key]),original.themeDrafts[other.key]);});
test('unsupported theme value has no result; source change and editing invalidate adoption',()=>{let state=confirm(model.createInitialState(),'margin');state=send(state,{type:'theme-edit',theme:'margin',value:'123'});state=send(state,{type:'theme-preview',theme:'margin'});assert.match(state.themeDrafts.margin.error,/fixture/);state=send(state,{type:'theme-edit',theme:'margin',value:'130'});state=send(state,{type:'theme-preview',theme:'margin'});state=send(state,{type:'theme-simulate',theme:'margin',id:'s1',at:'today'});state=send(state,{type:'source-fact',sourceId:'source-supplier',factId:'fact-margin',status:'removed'});state=send(state,{type:'scenario-apply',id:'s1',versionId:'v1',at:'today'});assert.equal(state.themeVersions.length,0);assert.match(state.themeDrafts.margin.error,/périmée/);});
test('restoration creates a new version, retains history, undo restores previous draft',()=>{let state=confirm(model.createInitialState(),'people');state=send(state,{type:'theme-preview',theme:'people'});state=send(state,{type:'theme-simulate',theme:'people',id:'s1',at:'today'});state=send(state,{type:'scenario-apply',id:'s1',versionId:'v1',at:'today'});state=send(state,{type:'theme-edit',theme:'people',value:'2027-01-01'});const old=plain(state.themeVersions);state=send(state,{type:'version-restore',id:'v1',versionId:'v2',at:'tomorrow'});assert.deepEqual(plain(state.themeVersions.slice(1)),old);state=send(state,{type:'theme-undo',theme:'people'});assert.equal(state.themeDrafts.people.value,'2027-01-01');assert.equal(state.themeVersions[0].id,'v2');});
test('monthly preview requires exact example period and mapping; confirmation never changes reference',()=>{let state=model.createInitialState(),reference=JSON.stringify(state.referenceVersions);state=send(state,{type:'monthly-start',period:'2026-09',fileName:'Example'});state=send(state,{type:'monthly-preview'});assert.equal(state.monthlyImport.status,'mapping');state=send(state,{type:'monthly-start',period:'2026-08',fileName:'Example'});state=send(state,{type:'monthly-map',column:'encaissements',metric:'cash_receipts'});state=send(state,{type:'monthly-map',column:'achats',metric:'purchases'});state=send(state,{type:'monthly-preview'});assert.equal(state.monthlyImport.status,'preview');state=send(state,{type:'monthly-confirm'});assert.equal(state.monthlyImport.status,'confirmed');assert.equal(JSON.stringify(state.referenceVersions),reference);});
test('foreign dossier facts cannot confirm a theme or alter local sources',()=>{let state=model.createInitialState();const foreign={id:'foreign',caseId:'another-case',title:'Not this case',kind:'example',facts:[{id:'foreign-fact',label:'Cost',value:'120',status:'confirmed',themes:['margin']}]};state=send(state,{type:'source-add',source:foreign});assert.equal(state.sources.some(s=>s.id==='foreign'),false);const corrupted={...state,sources:[...state.sources,foreign]};assert.equal(catalog.sourceConfirmed(corrupted,'margin'),false);assert.strictEqual(send(corrupted,{type:'source-fact',sourceId:'foreign',factId:'foreign-fact',value:'999',status:'confirmed'}),corrupted);});
test('confirming the same source twice does not invalidate a prepared simulation',()=>{let state=confirm(model.createInitialState(),'margin');state=send(state,{type:'theme-preview',theme:'margin'});state=send(state,{type:'theme-simulate',theme:'margin',id:'s1',at:'today'});const same=confirm(state,'margin');assert.strictEqual(same,state);state=send(same,{type:'scenario-apply',id:'s1',versionId:'v1',at:'today'});assert.equal(state.themeVersions.length,1);});
test('a scenario based on a replaced version cannot be adopted by reloading its old inputs',()=>{let state=confirm(model.createInitialState(),'investment');state=send(state,{type:'theme-preview',theme:'investment'});state=send(state,{type:'theme-simulate',theme:'investment',id:'old',at:'today'});state=send(state,{type:'theme-edit',theme:'investment',value:'2027-01-01'});state=send(state,{type:'theme-preview',theme:'investment'});state=send(state,{type:'theme-simulate',theme:'investment',id:'new',at:'today'});state=send(state,{type:'scenario-apply',id:'new',versionId:'v1',at:'today'});state=send(state,{type:'scenario-load',id:'old'});state=send(state,{type:'scenario-apply',id:'old',versionId:'v2',at:'today'});assert.equal(state.themeVersions.length,1);assert.match(state.themeDrafts.investment.error,/périmée/);});
