import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import ts from 'typescript';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const origin='http://127.0.0.1:5175';
const folder=path.resolve('../runtime/cockpit-demo-ui-'+new Date().toISOString().replace(/[:.]/g,'-'));
fs.mkdirSync(folder,{recursive:true});
function compile(file,deps={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports,require:id=>deps[id]});return exports;}
const catalog=compile('src/cockpit/lib/catalog.ts'),model=compile('src/cockpit/lib/demo.ts',{'./catalog':catalog});
function fingerprints(dir){return Object.fromEntries(fs.readdirSync(dir,{recursive:true,withFileTypes:true}).filter(x=>x.isFile()).map(x=>{const p=path.join(x.parentPath,x.name);return [p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')];}));}
const before=fingerprints('src/cockpit'),checks=[],issues=[],errors=[];
let server,browser,page;
function record(name,value={}){checks.push({name,...value});fs.writeFileSync(path.join(folder,'progress.json'),JSON.stringify({checks,issues},null,2));}
async function overflow(label){const widths=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));if(widths.scroll>widths.client+2){const elements=await page.evaluate(()=>Array.from(document.querySelectorAll('main *')).filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.right>innerWidth+2||r.left< -2)&&getComputedStyle(e).position!=='fixed';}).slice(0,12).map(e=>({tag:e.tagName,cls:e.className,text:e.textContent?.slice(0,70)})));issues.push({label,...widths,elements});}record(label,widths);}
try {
 try{await fetch(origin);throw Error('Port déjà occupé : recette annulée.');}catch(e){if(e.message.includes('occupé'))throw e;}
 server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5175','--strictPort'],{windowsHide:true,stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',d=>fs.appendFileSync(path.join(folder,'server.log'),d));
 for(let i=0;i<60;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,250));}
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});context.setDefaultTimeout(30000);
 const old=JSON.parse(JSON.stringify(model.createInitialState()));old.schemaVersion=1;old.brand.companyName='Recette migration';old.brand.firstName='Camille';old.brand.logoDataUrl='data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"><rect width="20" height="20" fill="#145f64"/></svg>').toString('base64');old.savedVariants=Array.from({length:4},(_,i)=>({id:'legacy-'+i,name:'Conservé '+i,createdAt:'Avant migration',inputs:old.contract,metrics:old.referenceMetrics}));delete old.sources;delete old.themeDrafts;delete old.themeScenarios;delete old.themeVersions;
 await context.addInitScript(old=>{if(!localStorage.getItem('cockpit-demo:v1')&&!localStorage.getItem('cockpit-demo:v2'))localStorage.setItem('cockpit-demo:v1',JSON.stringify(old));},old);
 page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/demo');await page.getByRole('heading',{name:/Bonjour Camille/}).waitFor();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cockpit-demo:v2')||'null')?.schemaVersion===2);const migrated=await page.evaluate(()=>JSON.parse(localStorage.getItem('cockpit-demo:v2')));assert.equal(migrated.savedVariants.length,4);assert.equal(migrated.brand.logoDataUrl,old.brand.logoDataUrl);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cockpit-demo:v1')).schemaVersion),1);record('v1 migration preserves logo, brand, four variants and old key');
 // Confirm all palette choices via the visible editor; persistence and inherited variables are checked after navigation.
 for(const palette of model.defaultPalettes){await page.goto(origin+'/demo/parcours/installation?mode=review&step=1');await page.getByRole('button',{name:palette.label,exact:true}).click();await page.getByRole('button',{name:'Enregistrer mes changements',exact:true}).click();await page.getByRole('heading',{name:'Votre parcours, à votre rythme.',exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cockpit-demo:v2')).brand.palette.id),palette.id);await page.screenshot({path:path.join(folder,'palette-'+palette.id+'.png'),fullPage:true});record('palette:'+palette.id);}
 // Unsaved setup: push, cancel, save-to-intended-destination and browser Back all go through the same guard.
 await page.goto(origin+'/demo/livrables');await page.getByRole('link',{name:'Personnaliser',exact:true}).click();await page.getByLabel('Nom de l’entreprise').fill('Changement non enregistré');await page.getByRole('link',{name:'Simulations',exact:true}).first().click();await page.getByRole('heading',{name:'Garder vos changements avant de partir ?',exact:true}).waitFor();assert.ok(page.url().includes('/parcours/installation'));await page.getByRole('button',{name:'Rester ici',exact:true}).click();assert.equal(await page.getByLabel('Nom de l’entreprise').inputValue(),'Changement non enregistré');await page.getByRole('button',{name:'Continuer',exact:true}).click();await page.getByRole('heading',{name:'Votre identité visuelle',exact:true}).waitFor();await page.evaluate(()=>history.back());await page.getByLabel('Nom de l’entreprise').waitFor();assert.equal(await page.getByLabel('Nom de l’entreprise').inputValue(),'Changement non enregistré');record('setup internal steps preserve local draft');
 const unload=await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;});assert.equal(unload,true);record('setup beforeunload veto installed');
 await page.evaluate(()=>history.back());await page.getByRole('heading',{name:'Garder vos changements avant de partir ?',exact:true}).waitFor();await page.getByRole('button',{name:'Rester ici',exact:true}).click();assert.ok(page.url().includes('/parcours/installation'));await page.getByRole('link',{name:'Simulations',exact:true}).first().click();await page.getByRole('button',{name:'Enregistrer et terminer',exact:true}).click();await page.waitForURL('**/demo/simulations');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cockpit-demo:v2')).brand.companyName),'Changement non enregistré');record('setup push/back guard, cancellation, save and intended destination');
 await page.getByRole('link',{name:'Personnaliser',exact:true}).click();await page.getByLabel('Nom de l’entreprise').fill('À abandonner');await page.getByRole('link',{name:'Livrables',exact:true}).first().click();await page.getByRole('button',{name:'Quitter sans garder',exact:true}).click();await page.waitForURL('**/demo/livrables');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cockpit-demo:v2')).brand.companyName),'Changement non enregistré');record('setup explicit discard preserves saved brand');
 await page.goto(origin+'/demo/suivi-mensuel');await page.getByRole('button',{name:'Choisir cet exemple',exact:true}).click();await page.getByLabel('Correspondance encaissements').selectOption('cash_receipts');await page.getByLabel('Correspondance achats').selectOption('purchases');await page.getByRole('button',{name:'Examiner l’import fictif',exact:true}).click();await page.getByRole('button',{name:'Confirmer cet exemple de réalisé',exact:true}).click();record('monthly tables populated before responsive checks');
 const routes=['','/travail/ventes','/travail/couts','/expert/feuilles/cashflow?vue=grille','/suivi-mensuel','/livrables','/parcours/installation?mode=review&step=3'];
 for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:1000});for(const route of routes){await page.goto(origin+'/demo'+route);await page.locator('h1').last().waitFor();await overflow('responsive:'+width+':'+route);if(route===''||width===320&&route.includes('cashflow'))await page.screenshot({path:path.join(folder,'width-'+width+(route?'cashflow':'home')+'.png'),fullPage:true});}}
 await page.setViewportSize({width:1440,height:1000});await page.goto(origin+'/demo/travail/couts');await page.getByLabel('Coût unitaire (EUR / unité)',{exact:true}).fill('130');await page.getByLabel('Coût unitaire (EUR / unité)',{exact:true}).press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement?.tagName),'BODY');record('keyboard input and Tab focus');
 await page.evaluate(()=>document.documentElement.style.zoom='2');await overflow('zoom200-percent');await page.screenshot({path:path.join(folder,'zoom200.png'),fullPage:true});await page.evaluate(()=>document.documentElement.style.zoom='');
 const motion=await page.locator('.companion-mark__form').first().evaluate(e=>getComputedStyle(e).animationName);assert.equal(motion,'none');record('reduced motion companion animation disabled');
 const css=fs.readFileSync('src/cockpit/app/globals.css','utf8'),start=css.indexOf('@supports not'),open=css.indexOf('{',start);let depth=1,end=open+1;for(;depth>0&&end<css.length;end++){if(css[end]==='{')depth++;else if(css[end]==='}')depth--;}await page.addStyleTag({content:css.slice(open+1,end-1)});await page.waitForFunction(()=>getComputedStyle(document.querySelector('.nav-island')).backdropFilter==='none');const fallback=await page.locator('.nav-island').first().evaluate(e=>({background:getComputedStyle(e).backgroundColor,filter:getComputedStyle(e).backdropFilter}));assert.equal(fallback.filter,'none');assert.match(fallback.background,/0.96/);await page.screenshot({path:path.join(folder,'fallback-solid.png'),fullPage:true});record('fallback CSS branch explicitly applied',{...fallback,note:'Unsupported browser is emulated by applying the existing @supports-not rules.'});
 assert.deepEqual(errors,[]);const after=fingerprints('src/cockpit'),changed=Object.keys(before).filter(p=>before[p]!==after[p]);fs.writeFileSync(path.join(folder,'receipt.json'),JSON.stringify({status:issues.length?'UI_ISSUES':'PASS_DEMO_UI',checks,issues,errors,sourceFilesChangedDuringRun:changed},null,2));console.log(JSON.stringify({status:issues.length?'UI_ISSUES':'PASS_DEMO_UI',checks:checks.length,issues:issues.length,folder}));if(issues.length)process.exitCode=1;
} catch(error){if(page){try{fs.writeFileSync(path.join(folder,'failure-page.html'),await page.content());await page.screenshot({path:path.join(folder,'failure-page.png'),fullPage:true});}catch{}}fs.writeFileSync(path.join(folder,'failure.json'),JSON.stringify({message:String(error),checks,issues,errors},null,2));console.error(error);process.exitCode=1;}
finally {await browser?.close();server?.kill();}
