import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";
import { createHash } from "node:crypto";

test("backend réel isolé : dossier, source, brouillon sourcé, lecture persistée et téléchargement sans Excel", async ({ page }, testInfo) => {
  const name = "Recette navigateur " + new Date().toISOString().replace(/[:.]/g, "-"), errors: string[] = [], mutations: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => { if (["POST", "PUT", "DELETE"].includes(request.method()) && request.url().includes("/api/")) mutations.push(new URL(request.url()).pathname); });
  await page.goto("/atelier");
  await page.getByRole("button", { name: "Nouveau dossier", exact: true }).click();
  await page.getByLabel("Organisation ou client").fill("Organisation fictive · recette web");
  await page.getByLabel("Nom du dossier", { exact: true }).fill(name);
  await page.getByRole("button", { name: "Créer le dossier", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  const caseId = await page.evaluate(() => localStorage.getItem("tca.case")); expect(caseId).toBeTruthy();
  await page.getByRole("button", { name: /^Sources \d+$/ }).click();
  await page.getByRole("button", { name: "Ajouter une source", exact: true }).click();
  await page.getByLabel("Titre", { exact: true }).fill("Calendrier fictif de recette");
  await page.getByLabel("Contenu", { exact: true }).fill("Recette navigateur uniquement : début du prévisionnel en 2027. Cette valeur fictive est proposée au brouillon, sans calcul ni adoption dans Excel.");
  await page.getByRole("button", { name: "Ajouter la source", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByLabel("Source de la saisie").selectOption({ label: "Calendrier fictif de recette" });
  await page.getByRole("button", { name: /^Feuilles \d+$/ }).click();
  await page.locator(".sheet-item").filter({ has: page.getByText("Control", { exact: true }) }).click();
  await page.getByLabel("Adresse de cellule").fill("C10"); await page.getByLabel("Adresse de cellule").press("Enter");
  await page.getByLabel("Valeur ou formule de la cellule").fill("01/01/2027");
  await page.getByRole("button", { name: "Ajouter la valeur au brouillon" }).click();
  await expect(page.getByRole("button", { name: "Voir le lot", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Voir le lot", exact: true }).click();
  await expect(page.getByRole("cell", { name: "Control · C10", exact: true })).toBeVisible();
  await expect(page.getByRole("cell", { name: "2027-01-01", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Appliquer en nouvelle version", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Fermer", exact: true }).click();
  await page.reload(); await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Voir le lot", exact: true })).toBeEnabled();
  const draftResponse = await page.request.get(`/api/cases/${caseId}/draft`), draft = await draftResponse.json();
  expect(draft.operations).toEqual(expect.arrayContaining([expect.objectContaining({ type: "set_value", sheet: "Control", cell: "C10", value: "2027-01-01", evidence_id: expect.any(String) })]));
  const detail = await (await page.request.get(`/api/cases/${caseId}`)).json(); expect(detail.revision).toBe(0);
  const downloadEvent = page.waitForEvent("download"); await page.getByRole("button", { name: "Classeur", exact: true }).click();
  const download = await downloadEvent; expect(download.suggestedFilename()).toMatch(/\.xlsm$/i);
  expect(await download.failure()).toBeNull();
  const stream = await download.createReadStream(), hash = createHash("sha256"); let downloadSize = 0, signature = "";
  for await (const chunk of stream) { if (!downloadSize) signature = chunk.subarray(0, 4).toString("hex"); downloadSize += chunk.length; hash.update(chunk); }
  expect(downloadSize).toBeGreaterThan(10000); expect(signature).toBe("504b0304"); const downloadSha = hash.digest("hex");
  await page.screenshot({ path: testInfo.outputPath("backend-reel-dossier-fictif.png"), fullPage: true });
  expect(mutations.some(path => /\/(preview|apply|recalculate|chat|retry)$/.test(path))).toBe(false);
  expect(errors).toEqual([]);
  await fs.writeFile(testInfo.outputPath("receipt.json"), JSON.stringify({ status: "PASS", case_id: caseId, name, revision: detail.revision, draft_status: draft.status, operations: draft.operations.length, download_bytes: downloadSize, download_sha256: downloadSha, mutations, browser_errors: errors, no_excel: true, no_provider_call: true, scope: "Dossier/source/brouillon/persistance/flux téléchargé : serveur réel. Aucune application ni recette native Excel." }, null, 2));
});
