import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";

test("serveur réel qualifié : valider le réalisé puis lire le formulaire de raccord sans préparer le classeur", async ({ page }, testInfo) => {
  test.skip(!process.env.TCA_WEB_QUALIFIED_CASE, "Nécessite une copie fictive déjà recalculée et qualifiée ; aucun Excel n’est lancé par ce test.");
  const caseId = process.env.TCA_WEB_QUALIFIED_CASE!;
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.addInitScript(id => { localStorage.setItem("tca.case", id); localStorage.setItem("tca.page." + id, "actuals"); }, caseId);
  const initialResponse = await page.request.get(`/api/cases/${caseId}`); expect(initialResponse.ok()).toBeTruthy();
  const initial = await initialResponse.json(); expect(initial.outputs_current).toBe(true);
  const draftBefore = await (await page.request.get(`/api/cases/${caseId}/draft`)).json();
  await page.goto("/atelier");
  await expect(page.getByRole("heading", { name: initial.name, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Réalisé", exact: true }).click();
  await page.getByLabel("Date d’arrêté du réalisé").fill("2026-01-31");
  const values = { revenue: 10000, net_income: 6000, receipts: 10000, payments: 4000, cash: 106000, assets: 106000, liabilities: 0, equity: 106000, receivables: 0, payables: 0, inventory: 0, debt: 0 };
  const csv = "period;metric;value\n" + Object.entries(values).map(([metric, value]) => `2026-01;${metric};${value}`).join("\n");
  await page.getByLabel("Fichier du réalisé").setInputFiles({ name: "recette-mathematique-fictive-janvier-2026.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
  await page.getByRole("button", { name: "Lire les colonnes du fichier" }).click();
  await page.getByRole("combobox", { name: "Période", exact: true }).selectOption("period");
  await page.getByRole("combobox", { name: "Poste métier", exact: true }).selectOption("metric");
  await page.getByRole("combobox", { name: "Valeur", exact: true }).selectOption("value");
  await page.getByRole("button", { name: "Prévisualiser les lignes importées" }).click();
  const preview = page.getByRole("dialog", { name: "Aperçu du réalisé" });
  await expect(preview).toBeVisible();
  await page.getByRole("button", { name: "Approuver et adopter", exact: true }).click();
  await expect(preview).toHaveCount(0);
  await page.getByText("Préparer le raccord du réalisé dans Excel", { exact: true }).click();
  await expect(page.getByRole("button", { name: "Préparer le raccord dans Excel", exact: true })).toBeEnabled();
  await expect(page.getByLabel("Total actif du modèle à l’arrêté", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Total actif du modèle à l’arrêté", { exact: true })).not.toHaveAttribute("readonly");
  await page.getByText("Trésorerie · À définir", { exact: true }).click();
  await expect(page.getByLabel("Traitement : Trésorerie", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Fin d’horizon : Trésorerie", { exact: true })).toHaveValue("");
  await expect(page.getByRole("heading", { name: "Informations de raccord à compléter" })).toBeVisible();
  const actuals = await (await page.request.get(`/api/cases/${caseId}/actuals`)).json();
  expect(actuals.rows).toHaveLength(12); expect(actuals.budget.source_sha256).toBe(initial.sha256);
  expect(actuals.forecast_status).toBe("A_PREPARER");
  const requirements = await (await page.request.get(`/api/cases/${caseId}/actuals/bridge/questions`)).json();
  expect(requirements.baseline_fields).toHaveLength(4); expect(requirements.baseline_fields.every((field: { linked: boolean }) => !field.linked)).toBe(true);
  const current = await (await page.request.get(`/api/cases/${caseId}`)).json(); expect(current.revision).toBe(initial.revision); expect(current.sha256).toBe(initial.sha256);
  const draftAfter = await (await page.request.get(`/api/cases/${caseId}/draft`)).json(); expect(draftAfter.operations).toEqual(draftBefore.operations);
  expect(errors).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("raccord-local-a-completer.png"), fullPage: true });
  await fs.writeFile(testInfo.outputPath("receipt.json"), JSON.stringify({ status: "PASS", caseId, financial_revision: current.revision, actuals_count: actuals.rows.length, budget_source_sha256: actuals.budget.source_sha256, forecast_status: actuals.forecast_status, baseline_fields: requirements.baseline_fields, questions: requirements.questions.length, no_draft_preparation: true, no_excel_execution: true, no_provider_call: true, browser_errors: errors }, null, 2));
});