import { expect, test } from '@playwright/test';
import fs from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import type { Catalog, SheetView } from '../src/connected/types';

test('cockpit et API réels : dossier fictif, identité de feuille, source, saisie persistée et grille protégée', async ({ page }, testInfo) => {
  const errors: string[] = [], mutations: { method: string; path: string }[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET') mutations.push({ method: request.method(), path: new URL(request.url()).pathname }); });
  const created = await page.request.post('/api/cases', { data: { client_name: 'Entreprise fictive recette cockpit', name: 'Cockpit réel ' + randomUUID() } });
  expect(created.status()).toBe(200);
  const createdBody = await created.json(), id = (createdBody.case || createdBody).id;
  const base = '/api/cases/' + encodeURIComponent(id);
  const before = await (await page.request.get(base)).json();
  const catalogResponse = await page.request.get(base + '/cockpit/catalog'); expect(catalogResponse.status()).toBe(200);
  const catalog = await catalogResponse.json() as Catalog;
  const control = catalog.sheets.find(sheet => sheet.original_name === 'Control'); expect(control).toBeTruthy();
  const windowResponse = await page.request.get(base + '/cockpit/sheets/' + encodeURIComponent(control!.id) + '?limit=500'); expect(windowResponse.status()).toBe(200);
  const sheetWindow = await windowResponse.json() as SheetView;
  const entry = sheetWindow.entries.find(entry => entry.cell === 'C59' && entry.editable && !entry.calculated);
  expect(entry, 'Horizon reconnu par le catalogue et éditable, sans formule remplacée').toBeTruthy();
  const proposed = entry!.current_value === 6 ? 7 : 6;
  await page.addInitScript(caseId => localStorage.setItem('tca.case', caseId), id);
  await page.goto('/expert/feuilles/' + encodeURIComponent(control!.id));
  await expect(page.getByRole('heading', { name: control!.label, exact: true })).toBeVisible();
  const field = page.getByLabel(entry!.label + ' · ' + entry!.cell, { exact: true });
  await field.fill(String(proposed));
  await page.getByRole('button', { name: 'Ajouter une source', exact: true }).click();
  await page.getByLabel('Titre', { exact: true }).fill('Hypothèse de recette cockpit');
  await page.getByLabel('Contenu', { exact: true }).fill(`Document fictif de recette : horizon proposé de ${proposed} années civiles. Ne pas utiliser pour un client.`);
  await page.getByRole('button', { name: 'Ajouter la source', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Ajouter une source', exact: true })).not.toBeVisible();
  const sources = (await (await page.request.get(base + '/sources')).json()).sources;
  const source = sources.find((item: { title: string }) => item.title === 'Hypothèse de recette cockpit'); expect(source).toBeTruthy();
  await expect(field).toHaveValue(String(proposed));
  await page.getByLabel('Source des modifications', { exact: true }).selectOption(source.id);
  const proposedResponse = page.waitForResponse(response => response.url().endsWith('/cockpit/answers') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Proposer 1 modification(s) au brouillon', exact: true }).click();
  const proposal = await proposedResponse;
  expect(proposal.status(), await proposal.text()).toBe(200);
  await expect(page.getByRole('dialog', { name: 'Brouillon partagé' })).toBeVisible();
  const draft = await (await page.request.get(base + '/draft')).json();
  expect(draft.operations).toEqual(expect.arrayContaining([expect.objectContaining({ type: 'set_value', sheet: control!.name, cell: entry!.cell, value: proposed })]));
  const draftDialog = page.getByRole('dialog', { name: 'Brouillon partagé' });
  const dialogBounds = await draftDialog.boundingBox();
  expect(dialogBounds).toBeTruthy();
  expect(Math.abs(dialogBounds!.x + dialogBounds!.width / 2 - 720), 'La fenêtre héritée reste centrée après intégration des styles du cockpit').toBeLessThan(2);
  await page.screenshot({ path: testInfo.outputPath('cockpit-brouillon-api-reelle.png'), fullPage: true });
  await page.getByRole('button', { name: 'Fermer', exact: true }).click();
  await page.reload();
  await expect(field).toHaveValue(String(proposed));
  await page.getByRole('button', { name: 'Grille Excel', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Discuter de cette sélection' })).toBeVisible();
  const address = page.getByLabel('Adresse de cellule', { exact: true });
  const formulaBar = page.getByLabel('Valeur ou formule de la cellule', { exact: true });
  await address.fill(entry!.cell);
  await address.press('Enter');
  await expect(formulaBar).toBeEditable();
  await expect(formulaBar).toHaveValue(String(proposed));
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: testInfo.outputPath('cockpit-grille-api-reelle.png'), fullPage: true });
  const cells = await (await page.request.get(base + '/cockpit/cells?sheet=' + encodeURIComponent(control!.name) + '&row=1&column=1&rows=100&columns=10')).json();
  expect(cells.cells.some((cell: { cell: string; editable?: boolean }) => cell.cell === entry!.cell && cell.editable)).toBe(true);
  const formulaCells = cells.cells.filter((cell: { formula?: string }) => cell.formula);
  expect(formulaCells.length, 'La recette vérifie de vraies cellules calculées présentes dans le classeur').toBeGreaterThan(0);
  expect(formulaCells.every((cell: { editable?: boolean }) => cell.editable === false)).toBe(true);
  await address.fill(formulaCells[0].cell);
  await address.press('Enter');
  await expect(formulaBar).toBeDisabled();
  await expect(formulaBar).toHaveValue('=' + formulaCells[0].formula.replace(/^=/, ''));
  const after = await (await page.request.get(base)).json();
  const jobs = (await (await page.request.get(base + '/jobs')).json()).jobs;
  expect(after.revision).toBe(before.revision); expect(after.sha256).toBe(before.sha256); expect(jobs).toHaveLength(0); expect(errors).toEqual([]);
  expect(mutations).toHaveLength(2); expect(mutations.map(request => request.path.split('/').slice(-2).join('/'))).toEqual([id + '/sources', 'cockpit/answers']);
  await fs.writeFile(testInfo.outputPath('receipt.json'), JSON.stringify({ status: 'PASS_REAL_COCKPIT_SOURCE_AND_DRAFT', case_id: id, before: { revision: before.revision, sha256: before.sha256 }, after: { revision: after.revision, sha256: after.sha256 }, sheet_id: control!.id, binding_id: entry!.binding_id, cell: entry!.cell, proposed, source_id: source.id, draft_id: draft.id, catalogue_sheet_count: catalog.sheets.length, persisted_after_reload: true, typed_draft_preserved_after_source_creation: true, calculated_cells_readonly: true, jobs_created: jobs.length, browser_errors: errors, browser_mutations: mutations, limits: ['Fictitious dossier and source only; no preview, adoption, native Excel calculation or AI provider call.'] }, null, 2));
});
