import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";

test("serveur réel : calendrier proposé, registres qualifiés et correspondance comptable en lecture", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const name = `Recette contrôles guidés ${Date.now()}`;
  await page.goto("/atelier"); await page.getByRole("button", { name: "Nouveau dossier", exact: true }).click();
  await page.getByLabel("Organisation ou client").fill("Organisation fictive de recette");
  await page.getByLabel("Nom du dossier", { exact: true }).fill(name);
  await page.getByRole("button", { name: "Créer le dossier", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  const caseId = await page.evaluate(() => localStorage.getItem("tca.case")); expect(caseId).toBeTruthy();
  const initial = await (await page.request.get(`/api/cases/${caseId}`)).json();
  await page.getByLabel("Première année", { exact: true }).fill("2027");
  await page.getByLabel("Horizon du prévisionnel").selectOption("2");
  await page.getByLabel("Démarrage de l’activité", { exact: true }).fill("2027-04-01");
  await page.getByRole("button", { name: "Enregistrer le profil", exact: true }).click();
  await expect(page.getByRole("button", { name: "Proposer ce calendrier au classeur" })).toBeEnabled();
  await page.getByRole("button", { name: "Proposer ce calendrier au classeur" }).click();
  await expect(page.getByRole("dialog", { name: "Brouillon partagé" })).toBeVisible();
  const draft = await (await page.request.get(`/api/cases/${caseId}/draft`)).json();
  expect(draft.operations.some((operation: { field_id?: string; cell?: string }) => operation.cell === "C10")).toBeTruthy();
  expect(draft.operations.some((operation: { cell?: string; value?: number }) => operation.cell === "C59" && operation.value === 2)).toBeTruthy();
  await page.getByRole("button", { name: "Fermer", exact: true }).click();
  await page.getByRole("button", { name: "Prévisionnel", exact: true }).click();
  await page.getByRole("button", { name: "Hypothèses guidées" }).click();
  await page.getByLabel("Registre métier").selectOption("Effectifs");
  await expect(page.getByRole("button", { name: "Préparer l’extension du registre" })).toBeVisible();
  const registers = await (await page.request.get(`/api/cases/${caseId}/registers`)).json();
  const other = registers.registers.find((register: { sheet: string; can_extend: boolean }) => !register.can_extend);
  expect(other).toBeTruthy();
  await page.getByLabel("Registre métier").selectOption(other.sheet);
  await expect(page.getByRole("button", { name: "Préparer l’extension du registre" })).toHaveCount(0);
  await page.getByRole("button", { name: "Réalisé", exact: true }).click();
  await expect(page.getByRole("button", { name: "Préparer le raccord dans Excel" })).toHaveCount(0);
  await page.getByLabel("Date d’arrêté du réalisé").fill("2027-01-31");
  await page.getByLabel("Fichier du réalisé").setInputFiles({ name: "realise-fictif.csv", mimeType: "text/csv", buffer: Buffer.from("Mois;Libellé;Montant\n2027-01;CA;1234,50\n2027-01;Banque;6000", "utf8") });
  await page.getByRole("button", { name: "Lire les colonnes du fichier" }).click();
  await page.getByRole("combobox", { name: "Période", exact: true }).selectOption("Mois");
  await page.getByRole("combobox", { name: "Poste métier", exact: true }).selectOption("Libellé");
  await page.getByRole("combobox", { name: "Valeur", exact: true }).selectOption("Montant");
  await page.getByRole("button", { name: "Prévisualiser les lignes importées" }).click();
  await page.getByLabel("Correspondance du poste : CA", { exact: true }).selectOption("revenue");
  await page.getByLabel("Correspondance du poste : Banque", { exact: true }).selectOption("cash");
  const actualsResponse = page.waitForResponse(response => response.url().endsWith("/actuals/import"));
  await page.getByRole("button", { name: "Prévisualiser les lignes importées" }).click();
  const imported = await (await actualsResponse).json();
  expect(imported.rows.find((row: { metric: string }) => row.metric === "cash").kind).toBe("balance");
  await expect(page.getByRole("dialog", { name: "Aperçu du réalisé" })).toContainText("1234.5");
  await page.getByRole("button", { name: "Fermer l’aperçu", exact: true }).click();
  const actuals = await (await page.request.get(`/api/cases/${caseId}/actuals`)).json();
  expect(actuals.rows).toHaveLength(0);
  await page.getByLabel("Compte PCG", { exact: true }).fill("411000");
  await page.getByLabel("Solde signé (débit +, crédit −)", { exact: true }).fill("12 345,67");
  const response = page.waitForResponse(url => url.url().includes("/accounting/mapping?"));
  await page.getByRole("button", { name: "Consulter la correspondance" }).click();
  const mapped = await (await response).json();
  expect(mapped.applied).toBe(false); expect(mapped.matched_prefix).toBeTruthy();
  await expect(page.getByText("Compte de référence", { exact: true })).toBeVisible();
  const current = await (await page.request.get(`/api/cases/${caseId}`)).json();
  expect(current.revision).toBe(initial.revision);
  expect(errors).toEqual([]);
  await fs.writeFile(testInfo.outputPath("receipt.json"), JSON.stringify({ status: "PASS", caseId, draft_operations: draft.operations.length, original_revision: initial.revision, final_revision: current.revision, actuals_metric_mapping_preview: imported.rows, actuals_adopted: false, accounting_mapping: mapped, no_excel_execution: true, no_provider_call: true, browser_errors: errors }, null, 2));
});
