import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";

test("parcours guidé sur serveur réel : trois activités, source tabulaire et capitalisation approuvée", async ({ page }, testInfo) => {
  const errors: string[] = [], cases: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  for (const activity of ["recurring", "trading", "production"]) {
    const name = `Recette autonome ${activity} ${Date.now()}`;
    await page.goto("/atelier"); await page.getByRole("button", { name: "Nouveau dossier", exact: true }).click();
    await page.getByLabel("Organisation ou client").fill("Organisation fictive");
    await page.getByLabel("Nom du dossier", { exact: true }).fill(name);
    await page.getByRole("button", { name: "Créer le dossier", exact: true }).click();
    await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
    const caseId = await page.evaluate(() => localStorage.getItem("tca.case")); expect(caseId).toBeTruthy(); cases.push(caseId!);
    await page.getByLabel("Nom de l’entreprise").fill("Atelier fictif " + activity);
    await page.getByLabel("Activité", { exact: true }).selectOption(activity);
    await page.getByLabel("Horizon du prévisionnel").selectOption("10");
    await page.getByRole("button", { name: "Enregistrer le profil", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "Demande enregistrée" })).toBeVisible();
    const saved = await (await page.request.get(`/api/cases/${caseId}/profile`)).json();
    expect(saved.profile.activity).toBe(activity); expect(saved.profile.years).toBe(10);
  }
  const caseId = cases.at(-1)!;
  await page.getByRole("button", { name: "Scénarios", exact: true }).click();
  await page.getByLabel("Associé 1", { exact: true }).fill("Fondatrice fictive");
  await page.getByRole("button", { name: "Ajouter un tour", exact: true }).click();
  await page.getByLabel("Pool salarié cible (%)").fill("10");
  await page.getByRole("button", { name: "Calculer et examiner la dilution", exact: true }).click();
  await expect(page.getByRole("table", { name: "Répartition du capital pleinement dilué" })).toBeVisible();
  const before = await (await page.request.get(`/api/cases/${caseId}/capitalization`)).json(); expect(before.rounds).toHaveLength(0);
  await page.getByRole("button", { name: "Approuver et adopter", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const after = await (await page.request.get(`/api/cases/${caseId}/capitalization`)).json(); expect(after.rounds).toHaveLength(1);
  expect(Number(after.result.holders.find((h: { name: string }) => h.name === "Tour 1").percent)).toBeCloseTo(20, 7);
  await page.getByRole("button", { name: "Documents", exact: true }).click();
  await page.getByRole("button", { name: "Importer un document ou une réponse" }).click();
  await page.getByRole("button", { name: "Document", exact: true }).click();
  await page.locator('input[type="file"]').setInputFiles({ name: "ventes-fictives.csv", mimeType: "text/csv", buffer: Buffer.from("poste;montant\nVentes;1234,50\n", "utf8") });
  await page.getByRole("button", { name: "Ajouter la source", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "Extraire les informations", exact: true }).click();
  await expect(page.getByRole("button", { name: /Examiner les preuves/ })).toBeVisible({ timeout: 60000 });
  await page.getByRole("button", { name: /Examiner les preuves/ }).click();
  await expect(page.getByRole("dialog")).toContainText("1234,50");
  await page.getByRole("button", { name: "Fermer", exact: true }).click();
  await page.getByRole("button", { name: "Réalisé", exact: true }).click();
  await page.getByLabel("Date d’arrêté du réalisé").fill("2027-01-31");
  await page.getByLabel("Mois", { exact: true }).fill("2027-01");
  await page.getByLabel("Poste métier ligne 1").selectOption("revenue");
  await page.getByLabel("Valeur", { exact: true }).fill("1234,50");
  await page.getByRole("button", { name: "Vérifier le réalisé saisi" }).click();
  await expect(page.getByRole("dialog", { name: "Aperçu du réalisé" })).toBeVisible();
  await expect(page.getByRole("dialog")).toContainText("1234.5");
  const actuals = await (await page.request.get(`/api/cases/${caseId}/actuals`)).json(); expect(actuals.rows).toHaveLength(0);
  await page.getByRole("button", { name: "Fermer l’aperçu" }).click();
  await page.getByRole("button", { name: "Livrables", exact: true }).click();
  await expect(page.getByRole("button", { name: "Préparer les quatre livrables" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("parcours-local-livrables.png"), fullPage: true });
  expect(errors).toEqual([]);
  await fs.writeFile(testInfo.outputPath("receipt.json"), JSON.stringify({ status: "PASS", cases, capital_adopted: true, document_extraction: true, actuals_preview_only: true, no_excel_execution: true, no_provider_call: true, browser_errors: errors }, null, 2));
});
