import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";

test("serveur réel : qualification fiscale examinée et besoins du raccord lus sans calcul", async ({ page }, testInfo) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  const name = `Recette qualification ${Date.now()}`, reason = "Règles fictives retenues uniquement pour vérifier le parcours d’approbation.";
  await page.goto("/atelier"); await page.getByRole("button", { name: "Nouveau dossier", exact: true }).click();
  await page.getByLabel("Organisation ou client").fill("Entreprise fictive de qualification");
  await page.getByLabel("Nom du dossier", { exact: true }).fill(name);
  await page.getByRole("button", { name: "Créer le dossier", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  const caseId = await page.evaluate(() => localStorage.getItem("tca.case")); expect(caseId).toBeTruthy();
  const initial = await (await page.request.get(`/api/cases/${caseId}`)).json();
  await page.getByRole("button", { name: "Ajouter une source à la conversation", exact: true }).click();
  await page.getByLabel("Titre", { exact: true }).fill("Règles fictives pour la recette");
  await page.getByLabel("Contenu", { exact: true }).fill("Source fictive. Hypothèses fiscales françaises de recette uniquement, sans validité économique ou fiscale réelle. Période fictive 2020-2100.");
  await page.getByRole("button", { name: "Ajouter la source", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByLabel("Module à qualifier", { exact: true }).selectOption("REGLES_FISCALES");
  await expect(page.getByLabel("Application du module")).toBeDisabled();
  await page.getByLabel("Qualification de la déclaration").selectOption("HYPOTHESE");
  const sourceSelect = page.getByLabel("Source de la qualification");
  const sourceId = await sourceSelect.locator("option").nth(1).getAttribute("value"); expect(sourceId).toBeTruthy();
  await sourceSelect.selectOption(sourceId!);
  await page.getByLabel("Juridiction fiscale").fill("FR");
  await page.getByLabel("Début de validité fiscale").fill("2020-01-01");
  await page.getByLabel("Fin de validité fiscale").fill("2100-12-31");
  await page.getByLabel("Justification de la qualification").fill(reason);
  await page.getByRole("button", { name: "Examiner cette qualification" }).click();
  const preview = page.getByRole("dialog", { name: "Aperçu de la qualification" });
  await expect(preview).toContainText(reason); await expect(preview).toContainText("Hypothèse");
  const before = await (await page.request.get(`/api/cases/${caseId}/qualifications`)).json();
  expect(JSON.stringify(before.declarations)).not.toContain(reason);
  await page.getByRole("button", { name: "Approuver et adopter", exact: true }).click();
  await expect(preview).toHaveCount(0);
  const after = await (await page.request.get(`/api/cases/${caseId}/qualifications`)).json();
  expect(JSON.stringify(after.declarations)).toContain(reason);
  const requirementsResponse = await page.request.get(`/api/cases/${caseId}/actuals/bridge/questions`);
  expect(requirementsResponse.ok()).toBeTruthy();
  const requirements = await requirementsResponse.json();
  expect(requirements.baseline_fields).toHaveLength(4); expect(requirements.workbook_sha256).toBe(initial.sha256);
  expect(requirements.periods.length).toBeGreaterThan(0); expect(requirements.questions.length).toBeGreaterThan(0);
  const current = await (await page.request.get(`/api/cases/${caseId}`)).json(); expect(current.revision).toBe(initial.revision);
  expect(errors).toEqual([]);
  await fs.writeFile(testInfo.outputPath("receipt.json"), JSON.stringify({ status: "PASS", caseId, qualification_preview_before_adoption: true, sourceId, baseline_fields: requirements.baseline_fields, bridge_questions: requirements.questions.length, final_revision: current.revision, no_excel_execution: true, no_provider_call: true, browser_errors: errors }, null, 2));
});