import { useEffect, useState, type FormEvent } from "react";
import { api, casePath, displayValue, errorText, statusLabel, type IntentReviewRequest } from "./api";
import type { Draft, Job, Operation, Settings, Version } from "./types";
import { Button, Empty, JsonDetail, Modal, PageNavigation } from "./ui";

export function NewCaseDialog({ close, done }: { close: () => void; done: (caseId: string) => void }) {
  const [client, setClient] = useState(""), [name, setName] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try { const result = await api<{ id?: string; case?: { id: string } }>("/cases", "POST", { client_name: client.trim(), name: name.trim() }); const id = result.id || result.case?.id; if (!id) throw new Error("Le serveur n’a pas fourni l’identifiant du nouveau dossier."); done(id); }
    catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  return <Modal title="Nouveau dossier" onClose={close}><p className="muted">Un espace de travail avec son classeur, ses sources et son historique.</p><form className="form-stack" onSubmit={submit}><label>Organisation ou client<input autoFocus required value={client} onChange={e => setClient(e.target.value)} placeholder="Nom de l’organisation"/></label><label>Nom du dossier<input required value={name} onChange={e => setName(e.target.value)} placeholder="Business plan · développement"/></label>{error && <div className="inline-error" role="alert">{error}</div>}<div className="modal-footer"><Button type="button" onClick={close}>Annuler</Button><Button className="primary" disabled={busy || !client.trim() || !name.trim()}>{busy ? "Création…" : "Créer le dossier"}</Button></div></form></Modal>;
}

export function SourceDialog({ caseId, close, done }: { caseId: string; close: () => void; done: () => void }) {
  const [tab, setTab] = useState("text"), [title, setTitle] = useState(""), [text, setText] = useState(""), [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try {
      if (tab === "text") await api(casePath(caseId) + "/sources", "POST", { title: title.trim() || "Réponse utilisateur", text });
      else { if (!file) throw new Error("Choisissez un document."); const body = new FormData(); body.append("file", file); body.append("title", title.trim() || file.name); await api(casePath(caseId) + "/sources/upload", "POST", body); }
      done();
    } catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  return <Modal title="Ajouter une source" onClose={close}><div className="segmented"><button className={tab === "text" ? "active" : ""} onClick={() => setTab("text")}>Texte ou réponse</button><button className={tab === "file" ? "active" : ""} onClick={() => setTab("file")}>Document</button></div><form className="form-stack" onSubmit={submit}><label>Titre<input autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder="Hypothèses commerciales · septembre"/></label>{tab === "text" ? <label>Contenu<textarea rows={8} required value={text} onChange={e => setText(e.target.value)} placeholder="Collez vos informations, puis précisez leur origine et leur date."/></label> : <label className="drop-zone">{file ? file.name : "Choisir un document"}<small>PDF, Word, Excel, texte ou image scannée</small><input type="file" accept=".pdf,.docx,.xlsx,.xlsm,.csv,.txt,.md,.json,.png,.jpg,.jpeg,.tif,.tiff,.bmp" onChange={e => setFile(e.target.files?.[0] || null)}/>{file && <span>{(file.size / 1024).toLocaleString("fr-FR", { maximumFractionDigits: 0 })} Ko</span>}</label>}<p className="note">L’ajout d’une pièce ne modifie pas le classeur. Ses informations pourront alimenter les propositions du chat.</p>{error && <div className="inline-error" role="alert">{error}</div>}<div className="modal-footer"><Button type="button" onClick={close}>Annuler</Button><Button className="primary" disabled={busy || (tab === "text" ? !text.trim() : !file)}>{busy ? "Import…" : "Ajouter la source"}</Button></div></form></Modal>;
}

export function SettingsDialog({ close }: { close: () => void }) {
  const [settings, setSettings] = useState<Settings | null>(null), [key, setKey] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  useEffect(() => { const abort = new AbortController(); void api<Settings>("/settings", "GET", undefined, abort.signal).then(setSettings).catch(e => { if (!abort.signal.aborted) setError(errorText(e)); }); return () => abort.abort(); }, []);
  async function save(event: FormEvent) {
    event.preventDefault(); if (!settings) return; setBusy(true); setError(""); setNotice("");
    try { const result = await api<Settings>("/settings", "PUT", { base_url: settings.base_url, model: settings.model, ...(key ? { api_key: key } : {}) }); setSettings(result); setKey(""); setNotice("Configuration enregistrée sur ce poste."); }
    catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  async function test() {
    setBusy(true); setError(""); setNotice("");
    try { const result = await api<{ ok?: boolean; model_available?: boolean; models?: string[]; message?: string }>("/settings/test", "POST", {}); if (result.models) setSettings(current => current ? { ...current, models: result.models } : current); setNotice(result.ok === false ? result.message || "La connexion n’a pas été validée." : result.model_available === false ? "Connexion établie, mais le modèle enregistré n’est pas disponible." : result.message || "Connexion à la configuration enregistrée réussie."); }
    catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  return <Modal title="Réglages du chat" onClose={close}><p className="muted">Le chat utilise le fournisseur et le modèle configurés. Les données nécessaires à votre demande peuvent lui être transmises.</p>{settings ? <form className="form-stack" onSubmit={save}><label>Adresse API<input type="url" required value={settings.base_url || ""} onChange={e => setSettings({ ...settings, base_url: e.target.value })} placeholder="https://api.deepseek.com"/></label><label>Modèle<input required list="api-models" value={settings.model || ""} onChange={e => setSettings({ ...settings, model: e.target.value })}/><datalist id="api-models">{settings.models?.map(model => <option key={model} value={model}/>)}</datalist></label><label>Clé API<span className="field-hint">{settings.api_key_configured ? "Une clé est enregistrée. Laissez vide pour la conserver." : "Aucune clé enregistrée."}</span><input type="password" autoComplete="new-password" value={key} onChange={e => setKey(e.target.value)} placeholder={settings.api_key_configured ? "Conserver la clé enregistrée" : "Coller votre clé"}/></label><p className="note">La clé n’est ni stockée dans le navigateur, ni renvoyée par le serveur.</p>{error && <div className="inline-error" role="alert">{error}</div>}{notice && <div className="inline-notice" role="status">{notice}</div>}<div className="modal-footer"><Button type="button" disabled={busy} onClick={test}>Tester la configuration enregistrée</Button><Button className="primary" disabled={busy}>{busy ? "Traitement…" : "Enregistrer"}</Button></div></form> : error ? <div role="alert" className="inline-error">{error}</div> : <p>Chargement de la configuration…</p>}</Modal>;
}

export function operationLabel(op: Operation) {
  const labels: Record<string, string> = { set_value: "Valeur", set_formula: "Formule", extend_offer: "Ajouter une offre métier", extend_register: "Étendre un registre métier", insert_rows: "Insérer des lignes", delete_rows: "Supprimer des lignes", insert_columns: "Insérer des colonnes", delete_columns: "Supprimer des colonnes", add_sheet: "Ajouter une feuille", rename_sheet: "Renommer une feuille", move_sheet: "Déplacer une feuille", delete_sheet: "Supprimer une feuille" };
  return labels[op.type] || op.type;
}
export function IntentReviewDialog({ request, close, done }: { request: IntentReviewRequest; close: () => void; done: () => void }) {
  const [review, setReview] = useState<{ approval_token?: string; operation?: string; status?: string; summary?: string; current_revision?: number; result_available?: boolean } | null>(null);
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [attempt, setAttempt] = useState(0);
  const path = casePath(request.caseId) + "/intents/" + encodeURIComponent(request.requestId) + "/review";
  useEffect(() => { const controller = new AbortController(); setError(""); setReview(null); void api<typeof review>(path, "GET", undefined, controller.signal).then(setReview).catch(error => { if (!controller.signal.aborted) setError(errorText(error)); }); return () => controller.abort(); }, [path, attempt]);
  async function resolve() {
    if (!review?.approval_token || review.current_revision == null) return;
    setBusy(true); setError("");
    try { await api(path, "POST", { approval_token: review.approval_token, expected_revision: review.current_revision }); localStorage.removeItem(request.key); done(); }
    catch (error) { setError(errorText(error)); setReview(null); } finally { setBusy(false); }
  }
  return <Modal title="Examiner une demande interrompue" onClose={close}><p className="muted">Le résultat de cette demande n’a pas été acquitté. Examinez l’état conservé avant de décider de sa clôture.</p><p className="note">Dossier : {request.caseId} · demande : {request.requestId}</p>{review && <><p><strong>{statusLabel(review.operation || request.path.split("/").filter(Boolean).at(-1))}</strong> · {statusLabel(review.status)} · révision {review.current_revision ?? "—"}</p><p className="prewrap">{review.summary}</p>{review.result_available && <p className="note">Un résultat est conservé. Retrouvez-le dans le dossier avant de préparer une autre demande.</p>}</>}{error && <div className="inline-error" role="alert">{error}</div>}{!review && !error && <p>Lecture de l’état courant…</p>}<p>La clôture conserve les données et les preuves existantes. Elle ne relance aucune écriture, aucun calcul et aucun appel IA.</p><div className="modal-footer"><Button type="button" onClick={close}>Revenir au dossier</Button>{!review && error && <Button disabled={busy} onClick={() => setAttempt(value => value + 1)}>Relire l’état courant</Button>}<Button className="primary" disabled={busy || !review?.approval_token || review.current_revision == null} onClick={() => void resolve()}>Clôturer cette demande sans la rejouer</Button></div></Modal>;
}
export function DraftDialog({ draft, caseId, busy, close, preview, apply, discard, resolve, error }: { error?: string; caseId?: string; draft: Draft; busy: boolean; close: () => void; preview: () => void; apply: () => void; discard: () => void; resolve: (index: number, choice: "existing" | "incoming") => void }) {
  const ready = draft.status === "READY" && !!draft.approval_token && !draft.conflicts?.length;
  const [rowPage, setRowPage] = useState(0), [conflictPage, setConflictPage] = useState(0);
  const rowsCount = draft.changes?.length || draft.operations?.length || 0;
  const rowOffset = Math.min(rowPage, Math.max(0, Math.ceil(rowsCount / 200) - 1)) * 200;
  const conflictOffset = Math.min(conflictPage, Math.max(0, Math.ceil((draft.conflicts?.length || 0) / 20) - 1)) * 20;
  const manifest = (draft.validation as { preview_details?: { filename?: string; sha256?: string; size?: number; total_changes?: number } } | undefined)?.preview_details;
  useEffect(() => { setRowPage(0); setConflictPage(0); }, [draft.id, draft.status]);
  function snapshot(value: unknown) {
    if (value == null) return <span className="muted">Vide</span>;
    if (typeof value !== "object") return displayValue(value);
    const item = value as { value?: unknown; formula?: string | null };
    if (item.formula) return <div className="snapshot"><code>{item.formula.startsWith("=") ? item.formula : "=" + item.formula}</code>{item.value != null && <small>Valeur : {displayValue(item.value)}</small>}</div>;
    return item.value == null ? <span className="muted">Vide</span> : displayValue(item.value);
  }
  return <Modal title="Brouillon partagé" wide onClose={close}>{error && <div role="alert" className="inline-error">{error}</div>}<div className="draft-summary"><span className={"badge " + (ready ? "good" : "warning")}>{statusLabel(draft.status)}</span><span>{draft.operations?.length || 0} opérations · révision de départ {draft.revision ?? "—"}</span></div><p className="muted">Le tableau et les agents alimentent ce même lot. L’aperçu vérifie les modifications avant leur application à une nouvelle version.</p>
    {!!draft.conflicts?.length && <section className="conflicts"><h3>Décisions à prendre</h3><PageNavigation count={draft.conflicts.length} page={conflictPage} onPage={setConflictPage} label="conflits" size={20}/>{draft.conflicts.slice(conflictOffset, conflictOffset + 20).map(conflict => <div className="conflict" key={conflict.index}><div><strong>Proposition déjà présente</strong><JsonDetail value={conflict.existing}/><Button disabled={busy} onClick={() => resolve(conflict.index, "existing")}>Conserver cette proposition</Button></div><div><strong>Nouvelle proposition</strong><JsonDetail value={conflict.incoming}/><Button disabled={busy} onClick={() => resolve(conflict.index, "incoming")}>Retenir la nouvelle proposition</Button></div></div>)}</section>}
    <PageNavigation count={rowsCount} page={rowPage} onPage={setRowPage} label="modifications"/>{!!draft.changes?.length ? <><div className="draft-table-wrap"><table className="plain-table" aria-label="Aperçu des modifications avant et après"><thead><tr><th>Action</th><th>Feuille / cellule</th><th>Ancien</th><th>Nouveau</th></tr></thead><tbody>{draft.changes.slice(rowOffset, rowOffset + 200).map((raw, index) => { const change = raw as Operation & { before?: unknown; after?: unknown }; return <tr key={index}><td>{operationLabel(change)}</td><td>{change.sheet || change.name}{change.cell ? " · " + change.cell : ""}</td><td className="prewrap">{snapshot(change.before)}</td><td className="prewrap">{snapshot(change.after)}</td></tr>; })}</tbody></table></div></> : <div className="draft-table-wrap"><table className="plain-table"><thead><tr><th>Action</th><th>Feuille / cellule</th><th>Proposition</th></tr></thead><tbody>{draft.operations?.slice(rowOffset, rowOffset + 200).map((op, index) => <tr key={index}><td>{operationLabel(op)}</td><td>{op.sheet || op.name}{op.cell ? " · " + op.cell : ""}{op.index ? " · position " + op.index : ""}</td><td className="prewrap">{op.type === "set_formula" ? op.formula : op.type === "set_value" ? displayValue(op.value) || "Effacer la valeur" : op.name || (op.count ? `${op.count} élément(s)` : "—")}</td></tr>)}</tbody></table></div>}
    {manifest && caseId && <div className="round-card"><p>L’aperçu de structure affiché contient un échantillon. {manifest.total_changes != null ? `${manifest.total_changes.toLocaleString("fr-FR")} changements figurent dans le fichier complet.` : "Le fichier complet conserve tous les changements."} Consultez ce détail avant d’appliquer la variante.</p><a className="button" href={"/api" + casePath(caseId) + "/draft/preview-details"} download>Télécharger tous les changements de structure</a><p className="note">{manifest.filename} · {manifest.size != null ? (manifest.size / 1024).toLocaleString("fr-FR", { maximumFractionDigits: 0 }) + " Ko · " : ""}Empreinte SHA-256 : {manifest.sha256?.slice(0, 16) || "Non fournie"}…</p></div>}
    {draft.diagnostics != null && <details className="details-block" open={draft.status === "BLOCKED"}><summary>Contrôles du classeur</summary><JsonDetail value={draft.diagnostics}/></details>}
    <div className="modal-footer"><Button className="danger-text" disabled={busy || !draft.operations?.length} onClick={discard}>Vider le brouillon</Button><div className="button-group"><Button icon="search" disabled={busy || !draft.operations?.length || !!draft.conflicts?.length} onClick={preview}>Vérifier l’aperçu</Button><Button icon="check" className="primary" disabled={busy || !ready} onClick={apply}>Appliquer en nouvelle version</Button></div></div>
  </Modal>;
}

export function VersionsDialog({ versions, busy, close, restore, error }: { error?: string; versions: Version[]; busy: boolean; close: () => void; restore: (version: Version) => void }) {
  const [selected, setSelected] = useState<Version | null>(null);
  return <Modal title="Historique des versions" wide onClose={close}>{error && <div role="alert" className="inline-error">{error}</div>}{selected ? <div className="restore-review"><h3>Reprendre la révision {selected.revision ?? selected.id}</h3><p>Cette action crée une version à partir de la copie sélectionnée. Vérifiez qu’il s’agit bien du point de reprise souhaité.</p><p className="muted">{selected.created_at ? new Date(selected.created_at).toLocaleString("fr-FR") : ""} · {selected.kind}</p><div className="button-group"><Button onClick={() => setSelected(null)}>Retour à l’historique</Button><Button disabled={busy} className="primary" onClick={() => restore(selected)}>Restaurer en nouvelle version</Button></div></div> : versions.length ? <div className="versions-list">{versions.map(version => <div className="version-row" key={version.id}><span className="version-number">{version.revision ?? "•"}</span><div><strong>{version.current ? "Version courante" : "Révision " + (version.revision ?? version.id)}</strong><small>{version.created_at ? new Date(version.created_at).toLocaleString("fr-FR") : "Date non indiquée"} · {version.kind || "Classeur"}</small></div>{version.current ? <span className="badge good">Courante</span> : <Button disabled={busy} onClick={() => setSelected(version)}>Reprendre</Button>}</div>)}</div> : <Empty icon="history" title="Aucune version renvoyée"/>}</Modal>;
}

export function JobsDialog({ jobs, busy, close, retry, cancel, error }: { error?: string; jobs: Job[]; busy: boolean; close: () => void; retry: (job: Job) => void; cancel?: (job: Job) => void }) {
  return <Modal title="Historique des tâches" wide onClose={close}>{error && <div role="alert" className="inline-error">{error}</div>}<p className="muted">Une reprise réutilise la demande d’origine. Le serveur vérifie que son contexte correspond toujours au dossier.</p>{jobs.length ? <div className="versions-list">{jobs.map(job => <article className="job-history-row" key={job.id}><div><strong>{statusLabel(job.kind)}</strong><span className={"badge " + (job.status === "SUCCEEDED" ? "good" : "warning")}>{statusLabel(job.status)}</span><small>{job.created_at ? new Date(job.created_at).toLocaleString("fr-FR") : ""}</small></div>{job.error != null && <p className="inline-error">{errorText(job.error)}</p>}{["FAILED", "INTERRUPTED", "CANCELLED"].includes(job.status) && <Button disabled={busy} onClick={() => retry(job)}>Reprendre cette tâche</Button>}{cancel && ["QUEUED", "RUNNING"].includes(job.status) && job.kind.includes("sensitivity") && <Button onClick={() => cancel(job)}>Interrompre la campagne</Button>}</article>)}</div> : <Empty icon="history" title="Aucune tâche enregistrée"/>}</Modal>;
}

export function StructureDialog({ kind, sheet, index, close, submit }: { kind: string; sheet: string; index: number; close: () => void; submit: (op: Operation) => Promise<void> }) {
  const [name, setName] = useState(kind === "rename_sheet" ? sheet : ""), [role, setRole] = useState(""), [position, setPosition] = useState(index || 1), [count, setCount] = useState(1), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const title = operationLabel({ type: kind });
  async function save(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    const op: Operation = { type: kind, ...(kind !== "add_sheet" ? { sheet } : {}), ...(["add_sheet", "rename_sheet"].includes(kind) ? { name: name.trim() } : {}), ...(kind === "add_sheet" ? { role: role.trim() } : {}), ...(["move_sheet", "insert_rows", "delete_rows", "insert_columns", "delete_columns"].includes(kind) ? { index: position } : {}), ...(kind.endsWith("rows") || kind.endsWith("columns") ? { count } : {}) };
    try { await submit(op); close(); } catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  return <Modal title={title} onClose={close}><form className="form-stack" onSubmit={save}><p className="muted">Cette modification de structure sera ajoutée au brouillon et vérifiée dans l’aperçu.</p>{kind !== "add_sheet" && <p className="scope-pill">{sheet}</p>}{["add_sheet", "rename_sheet"].includes(kind) && <label>Nom de la feuille<input autoFocus required maxLength={31} value={name} onChange={e => setName(e.target.value)}/></label>}{kind === "add_sheet" && <label>Rôle métier<textarea required rows={3} value={role} onChange={e => setRole(e.target.value)} placeholder="À quoi sert cette feuille et quelles informations doit-elle contenir ?"/></label>}{["move_sheet", "insert_rows", "delete_rows", "insert_columns", "delete_columns"].includes(kind) && <label>Position, à partir de 1<input type="number" min={1} required value={position} onChange={e => setPosition(Number(e.target.value))}/></label>}{(kind.endsWith("rows") || kind.endsWith("columns")) && <label>Nombre<input type="number" min={1} required value={count} onChange={e => setCount(Number(e.target.value))}/></label>}{kind === "delete_sheet" && <p>La suppression de cette feuille sera explicitement présentée dans le lot avant application.</p>}{error && <div className="inline-error" role="alert">{error}</div>}<div className="modal-footer"><Button type="button" onClick={close}>Annuler</Button><Button className="primary" disabled={busy || position < 1 || count < 1}>Ajouter au brouillon</Button></div></form></Modal>;
}

export function chartLine(values: (number | null)[], minimum: number, span: number, length: number) {
  let connected = false;
  return values.map((value, index) => {
    if (typeof value !== "number" || !Number.isFinite(value)) { connected = false; return ""; }
    const command = connected ? "L" : "M"; connected = true;
    return `${command}${75 + index / (length - 1) * 625},${225 - (value - minimum) / span * 195}`;
  }).join(" ");
}
type Chart = { name: string; title?: string; series: { name: string; categories: unknown[]; values: (number | null)[] }[] };
export function ChartsDialog({ data, close }: { data: { revision?: number; calculation_status?: string; charts: Chart[] }; close: () => void }) {
  const [index, setIndex] = useState(0), chart = data.charts[index];
  const numeric = chart?.series.flatMap(series => series.values.filter((v): v is number => typeof v === "number" && Number.isFinite(v))) || [];
  const min = Math.min(0, ...numeric), max = Math.max(1, ...numeric), span = max - min;
  const length = Math.max(2, ...chart?.series.map(series => series.values.length) || [2]);
  const colors = ["#267061", "#bf8350", "#697ec1", "#ac697d", "#5b9eb0", "#8e934e"];
  return <Modal title="Graphiques du classeur" wide onClose={close}><div className="draft-summary"><span>Révision {data.revision ?? "—"}</span><span className="badge warning">{statusLabel(data.calculation_status)}</span></div><p className="note">Valeurs enregistrées dans les graphiques du classeur. Un état « à recalculer » indique que ces valeurs peuvent être périmées.</p>{chart ? <><label className="form-stack">Graphique<select value={index} onChange={e => setIndex(Number(e.target.value))}>{data.charts.map((item, n) => <option key={n} value={n}>{item.title || item.name}</option>)}</select></label><h3>{chart.title || chart.name}</h3>{numeric.length ? <svg className="chart-plot" viewBox="0 0 720 270" role="img" aria-label={chart.title || chart.name}>{[0, .25, .5, .75, 1].map(tick => <g key={tick}><line x1={75} x2={700} y1={225 - tick * 195} y2={225 - tick * 195} stroke="#e3e9e4"/><text x={65} y={229 - tick * 195} textAnchor="end" fill="#738078" fontSize={11}>{new Intl.NumberFormat("fr-FR", { notation: "compact", maximumFractionDigits: 1 }).format(min + tick * span)}</text></g>)}{chart.series.map((series, n) => <g key={n}><path fill="none" stroke={colors[n % colors.length]} strokeWidth={2.5} d={chartLine(series.values, min, span, length)}><title>{series.name}</title></path>{series.values.map((value, i) => typeof value === "number" && Number.isFinite(value) ? <circle key={i} cx={75 + i / (length - 1) * 625} cy={225 - (value - min) / span * 195} r={3} fill={colors[n % colors.length]}><title>{series.name + ": " + value}</title></circle> : null)}</g>)}{chart.series[0]?.categories.map((category, i, categories) => i % Math.max(1, Math.ceil(categories.length / 7)) === 0 && <text key={i} x={75 + i / (length - 1) * 625} y={250} textAnchor="middle" fontSize={11} fill="#738078">{String(category).slice(0, 16)}</text>)}</svg> : <Empty icon="table" title="Aucune valeur numérique dans ce graphique"/>}<div className="chart-legend">{chart.series.map((series, n) => <span key={n}><i style={{ background: colors[n % colors.length] }}/>{series.name}</span>)}</div><details className="details-block"><summary>Valeurs sources du graphique</summary><JsonDetail value={chart.series}/></details></> : <Empty icon="table" title="Aucun graphique disponible"/>}</Modal>;
}
